### PR TITLE
WIP: `dvc pkg` cmd ref (and other misc updates)

### LINKED ISSUE #385: document `dvc import` and `dvc get` (previously `pkg` commands)
UPDATE: See description in https://github.com/iterative/dvc/pull/2160 instead.

---
OLD: Some introductory descriptions for DVC packages (from Discord):

> You have project named `awesome_project`, which has `awesome_data` in  it
  pkg will allow you to "import" the project
  `dvc pkg import awesome_project://awesome_data` (syntax may be incorrect)

> 1. Any DVC repo is a _package_. Outputs inside packages can be called _artifacts_ (that we'll also be able to work with)
> 2. There will be a set of commands to import/export these _packages_ across different repositories and from a repository to a file system ~~(just a data artifact)~~
> 3. basic use cases include things like: dataset registry (reuse a single dataset in multiple project, while having a single point of responsibility for the dataset itself), easy mechanism to pull a data artifact w/o doing `git clone` + `dvc pull data.dvc`, etc
> 4. in the future (no need to focus on this for now) any set of DVC files will be considered as package, thus making pipelines reusable

### PR DESCRIPTION
**Pull request by jorgeorpinel**
Review app may be at https://dvc-org-pr-417.herokuapp.com/ (enable at [CI pipeline](https://dashboard.heroku.com/pipelines/7a105706-a0cc-4e66-a022-2ea44c7cf238))

---
Closes #385

### CODE REVIEW

**Comment by efiop** [comment]
@jorgeorpinel I'm really sorry for switching back and forth, but pkg has changed again. https://github.com/iterative/dvc/pull/2160 Now there are no pkg commands at all. Regular `dvc import` is now `dvc import-url` and `dvc import` is now working with dvc repositories. We've also introduced `dvc get` that is like `dvc import` for dvc repostiroes(what we used to call packages), but only downloads data.

**Comment by ryokugyu** [comment]
@efiop Recently, `dvc pkg --force` option is also added.  

in this https://github.com/iterative/dvc/pull/2142

`dvc pkg` is being removed?

**Comment by efiop** [comment]
@ryokugyu Yes, the feature itself got reworked and there are no more `dvc pkg` commands.

**Comment by jorgeorpinel** [comment]
Thanks for the heads up @efiop and no worries, I haven't gotten around to this.

That makes sense too, BTW. Having both `import` and `pkg import` would've been confusing.

**Comment by shcheklein** [comment]
@jorgeorpinel closing this in favor of #464

**Pull request closed without merging**
