### PR TITLE
[accessibility] hide the mobile menu on desktop from keyboard users.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes the following from  #1149 

image

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
This is hard to check on https://dvc-landing-hide-menu-zp2dub1q.herokuapp.com/ because it doesn't include the focus visibility from #1153 so Idk where I am after every tab. But it seems like it's working. Please request our review here after #1153 is merged into master and then master into here 🙂

**Comment by jorgeorpinel** [comment]
Hey guys. There's a similar problem in https://dvc.org/doc: Once you get to the left sidebar with tabs, it seems to traverse all the collapsed (hidden) items. Should I open a specific issue for that or do you want to send a PR directly perhaps, @nisarhassan12?

**Comment by nisarhassan12** [comment]
Thanks! @jorgeorpinel I would send a Pr directly.

**Comment by nisarhassan12** [comment]
> Hey guys. There's a similar problem in https://dvc.org/doc: Once you get to the left sidebar with tabs, it seems to traverse all the collapsed (hidden) items. Should I open a specific issue for that or do you want to send a PR directly perhaps, @nisarhassan12?

@jorgeorpinel someone else can work on this.

**Comment by jorgeorpinel** [comment]
Sure np, thanks @nisarhassan12

**Pull request merged**
