### PR TITLE
Update events

### PR DESCRIPTION
**Pull request by andronovhopf**
I've updated the events section of the community page.

### CODE REVIEW

**Comment by andronovhopf** [comment]
@rogermparent good catch, i shrank it to 500x500

**Comment by shcheklein** [comment]
@andronovhopf @rogermparent so, it should 315 * 2 = 630 to look good on a modern screen, right?

**Comment by rogermparent** [comment]
Other images range around 500x500, so I think that's a good size!
I haven't heard of screens needing double the image size, but an image this simple isn't going to have any problems: especially the difference between 500x500 and 630x630.

As long as the data of the events themselves is good, I think this one is good to go.

**Comment by shcheklein** [comment]
@rogermparent it's a good practice to do 2x - https://www.danrodney.com/blog/retina-web-graphics-explained-1x-versus-2x-low-res-versus-hi-res/ (the first link that came). It's fine indeed to keep them ~2x, but 500 is already visible. Not a big deal though for this section.

**Pull request merged**
