### PR TITLE
Get started: data pipelines trail

### PR DESCRIPTION
**Pull request by omesser**
> You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

## changes:
- Introducing 3 distinct trails for get-started - specifically adding "data-pipelines" as was discussed and agreed in the past in other places, examples [here](https://github.com/iterative/dvc.org/pull/4460#pullrequestreview-1377904394), [here](https://github.com/iterative/dvc.org/pull/4460#issuecomment-1503184579)

- Changes to metrics/plots/params pages - based on changes here https://github.com/iterative/dvc.org/pull/4519

### CODE REVIEW

**Comment by shcheklein** [comment]
Hey, @omesser, thanks for trying to address this! It's a very large PR. Could we please outline the changes and agree on them (breaking the existing trail into pieces breaks the point of having trails the way they were intended- independent overviews of DVC features from different angles). Also, could we try to split and/or keep it precisely about one item, w/o polishing things around? That would help a lot thanks.

Also, how much a priority it is for us? I think we should callibrate wit Dave a bit on this. It doesn't feel very important considering the effort (eg we have release and docs for it, etc).

**Comment by omesser** [comment]
Hi @shcheklein  - thanks for the swift comment, notice this is still a draft, but already reviewable imo).

please see below detailed response:

> It's a very large PR. Could we please outline the changes and agree on them

updated the description with some links. @dberenbaum , @daavoo , and now me (I was unconvinced at first, but came around) believe that pipelines should be its own separate trail. This seems to be a more natural way to divide the mechanics and use-cases for DVC and communicate them for first-timers.

> breaking the existing trail into pieces breaks the point of having trails the way they were intended - independent overviews of DVC features from different angles).

That haven't changed actually. the trails are still as independent as they were but now data-pipelines is a 1st class citizen instead of something that is partially covered in both trails so you got 2 partial glimpses at the same feature/mechanism (which bothered me as well).
Currently - data trail does not cover experiment mechanics and vice versa. in other words, trails do not completely cover DVC functionality, but there's a lot of overlap. introducing pipelines trail does not change the fact trails are "incomplete" (it's fine, they shouldn't be complete), but it does create clearer conceptual boundaries and help digest DVC in what I believe are more logical chunks.

> Also, could we try to split and/or keep it precisely about one item, w/o polishing things around? That would help a lot thanks.

Actually, I first tried to do exactly that in #4519, leading with the change of refactoring metrics-plots-params page, but not isolating an independent pipelines trail yet. However... there was tons of pushback (from you 😉 ) , presumably because that change alone did not outline a clear enough value on its own, lacking the context of this PR.
So this is the "other way" - where the end goal is here - the new 3-trail structure.

> Also, how much a priority it is for us? I think we should callibrate wit Dave a bit on this. It doesn't feel very important considering the effort (eg we have release and docs for it, etc).

- this is coordinated with @dberenbaum (and @daavoo as mentioned). 
- priority - I do not agree this is not important. I think DVC get-started specifically is way more important than studio docs for example (highest visibility), it's first point-of-contact for many (let's talk about self-onboarding 😅 ), and we have ample inputs on changes needed there due to confusion. this includes internal feedback, and I think also explains why we have some many alternative 101s/intro-to-dvc/get-started in the wild.
- effort - this can be pretty low effort and easy win imo, as it's mostly moving existing content around and not generating new one. In the past few get-started changes (#4460, #4502, #4508, #4519, #4522) - the review cycles with @dberenbaum and @daavoo were short and efficient IMO. I think the "make or break" here is actually you @shcheklein 😄 - if you are not bought-in to the goals (3-trail concept, direction of get-started as a tutorial that is follow-able for non-dvc-experts), then it'll be very hard to move forward and might become a grind 😄 

So let's please have the HL discussion first, tell me if you agree to the approach / structure (or ok with leaving this to us to drive), before a more low-level review 🙏 

Thanks!

**Comment by shcheklein** [comment]
@omesser sorry, it seems I have to repeat a bit myself, since I'm not convinced still. 

- the idea of trails was to make them _independent_ representation of _all_ (or almost all) features of DVC from 2-3 different angles. 

> Currently - data trail does not cover experiment mechanics and vice versa. 

Related to this. It covers - https://dvc.org/doc/start/data-management/metrics-parameters-plots#updating-params-and-iterating. It's just outdated. We consciously don't spend time updating it since we have other priorities.

- if we talk about data pipelines as an independent trail it can't exist w/o basic `dvc add` for example, it should be covering data engineering related topics.
- if we are splitting and reusing the existing projects it breaks the logic of the existing content and the intention behind the trails. I would rather then go to the previous, simpler, trail-less iteration when we just had - "data management", "pipelines", and "experiments" (it was metrics, plots before) and we were using one single project. By doing what you are doing you are going in that direction (_not_ trails idea) but in bit sophisticated / indirect way.
- I still don't think it's a priority at the moment. Get started, landing page, landing for Studio - yes, 10x yes. Separate data pipelines trail? Why? Can you folks explain this a bit better to me? May be I'm missing something here.

----------

Some practical suggestions:

- Let's not touch other trails in the first PR. Just make a third one to review it independently. That would simplify everything.
- Let's first outline and discuss its content. What do we want to show there high level? What value - data pipelines, a way to organize projects, a way to run experiments? everything? (it's a bit of a hint here - in a lot of scenarios when I was thinking about this it was hard actually to make an independent trails for pipelines). This is a very important item to discuss and resolve. I think just moving content around won't move the needle. See one of the items above - it's better to get back to the pre-trail structure (that's what you are essentially doing in this PR to my mind, btw).
- Priority. It bothers me. I don't feel it this way. (just too many other pressing items on my plate?- Databricks, Sagemaker reseach, Studio landing, blog post, etc, etc - I feel overwhelmed already :( ).
 
---------

From a few discussions like this I start to believe tbh that the whole idea of trails was very wrong . I see that it's quite hard to align everyone on what they are, etc.

**Comment by omesser** [comment]
@shcheklein
Trying to avoid too many threads and walls-of-text. I'll try to focus on high level alignment:

I'm also repeating myself a bit here I'm afraid:
> So let's please have the HL discussion first, tell me if you agree to the approach / structure (or ok with leaving this to us to drive), before a more low-level review 🙏

The key friction point I'm getting from your comment here seems to be the implication of how it "mentally fits" with the original intent of trails.
- On one hand you're saying it breaks away from the original intent (covering all content from different angles) - even though that's not the state today even..
- but, on the other hand - you admit the original "trail" intent might not be the right direction anyways

I would like to suggest that insisting on "original intent" shouldn't be a key factor here. The "purity of the trails" as a concept should not be the golden reference, and is already not maintained as mentioned.
If we can move past the "initial intent" and try to make GS better it would be great! We shouldn't "fall in love" with past plans, if we get data that suggests the docs are confusing and practical ways to improve them.

To try and explain further - the reader doesn't have any expectation here that the trails 100% overlap, it's an internal personal decision that I'm not sure everyone share or even aware of, as a "restriction". Readers only expect that a trail will help them solve a specific problem or introduce a mechanism in conceptual terms that make sense and communicate how DVC can work for them.

I don't mind if we won't call them trails btw, or mentally say "we're moving in the direction of "tracks" or "chapters" or "modules". It's not important. But maybe this is something that I had to explicitly write here so it's clear.
What's most important to me is to convey the mental model and make it digest-able to readers in a non frustrating way (simple tutorial structure, linear, 0-knowledge to follow, non broken instructions, etc).

I hope this helps clarify some intentions and discussions that went offline. I don't want to go into more tactical details at this point just yet (e.g. `dvc add/remove` in pipelines-trail, using this or that project, it's all lower level), and I see no point in splitting this PR of making any code changes until we clear this up.

**Comment by omesser** [comment]
I would also re-iterate that this can be a low friction effort indeed (and I 100% respect you don't have attention to this), but it requires some "letting go" on your part I think, and delegation of decision making, and not just implementation, to @dberenbaum and @daavoo and myself. including prioritization and resource allocation to this.

**Comment by dberenbaum** [comment]
Sorry @omesser, I still haven't had a chance to review this. My plan is to get the entire experiments guide into a better place and then take a look at this one. 🙏

**Comment by omesser** [comment]
@dberenbaum There is no rush. Seems like it's blocked on the principle of introducing a new trail

**Pull request closed without merging**
