### PR TITLE
Regular updates (March 10)

### PR DESCRIPTION
**Pull request by jorgeorpinel**
- [x] Wait until #1014 is merged before reviewing/merging this.

- review terms "flag" and "option" per #608
- disambiguates terms "(command) option" vs "config option"

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
This PR is for after #1014 is merged.

**Comment by shcheklein** [comment]
@jorgeorpinel it's already 22 files, time to review :) ?

**Comment by jorgeorpinel** [comment]
@shcheklein OK I'll stop adding changes even when everything has to do with term "flag" and "option" but this needs to wait until the previous regular updates is merged, the file count will be reduced then.

**Comment by shcheklein** [comment]
@jorgeorpinel sounds good! will try to review that one today!

**Comment by jorgeorpinel** [comment]
Oops sorry Ivan, I guess this PR stayed big even after merging the previous ones 😢 and I have one last round of updates regarding the "options" term and some missing instances that should've ben done in the recent PRs, but will keep them stashed for a later PR after this.

**Comment by jorgeorpinel** [comment]
p.s. ah it did decrease from 22 to 19 files actually! I was seeing 30 when I wrote that ^ OK not so bad then. Still, keeping my current stash for now.

**Pull request merged**
