### PR TITLE
blog: merge some tags

### LINKED ISSUE #2340: blog: cleanup tags?
There's lots of single-use labels. Many could be removed or changed to a better one (with more usage). 

Full list (crude command that assumes no blog has more than 10 labels):

```
$ grep "tags:" content/blog/* -A 10 | awk '{print $2 " " $3}' | grep '^- ' | sort -f | uniq -c
      2 - Ambassador
      1 - Autocomplete
      1 - Azure
      1 - Benchmark
      3 - Best
      1 - Bitbucket
      1 - Blogging
      1 - Book
      2 - Cache
      9 - CI/CD
      1 - CLI
      1 - Cloud
     20 - CML
      1 - cml-send-comment
      1 - Completion
      1 - Conda
      2 - Conference
      3 - Continuous
      2 - DAGsHub
      2 - Data
      5 - DataOps
      3 - DevOps
     20 - Discord
      2 - DivOps
      2 - Docker
      2 - Documentation
     10 - DVC
      1 - echo
      1 - Engineering
      1 - External
      1 - GCP
     14 - Gems
      1 - Git
      2 - GitHub
      1 - GitLab
      8 - Google
      1 - gpu
      1 - GPUs
      3 - Hacktoberfest
     23 - Heartbeat
      1 - Homebrew
      2 - Hyperparameters
      2 - Import
      1 - Machine
      9 - Meetup
      2 - Mentoring
      1 - Metrics
      1 - MinIO
      1 - ML
     17 - MLOps
      1 - Model
      1 - Monorepo
      1 - New
      2 - Open
      1 - Optimization
      1 - Performance
      2 - Pipeline
      5 - Pipelines
      4 - Plots
      1 - Podcast
      1 - Productivity
      1 - Project
      1 - PTDC-18
      2 - PyCon
      1 - PyData
      5 - Python
      1 - PyTorch
      6 - R
      1 - Rclone
      1 - Reddit
      6 - Release
      2 - Reproducibility
      1 - RStats
      2 - SciPy
      1 - Self-hosted
      1 - shtab
      1 - spaCy
      1 - Spell
      1 - SSH
      1 - Students
      1 - Tab
      1 - Tags
      2 - Terraform
      5 - Tutorial
      2 - Udemy
      2 - Vega
      1 - Videos
      1 - Volunteer
      1 - YouTube
```
(That's the current output on `master`).

Obvious issues (examples):
- `DVC` should be used more or not used at all?
- `Pipeline` vs `Pipelines`
- `cml-send-comment` ? `PTDC-18`?
- `Project`, `Tab`, etc. - too broad
- `Video` and `YouTube` only used once (each)?

### PR DESCRIPTION
**Pull request by jorgeorpinel**
Fixes #2340

- [x] `Discord` + `Gems`
- [x] `CI/CD` consolidations
- [x] `PipelineS` (plural)
- [x] Consolidate `Python`

---

Should we

- [ ] Remove the few `DVC (1.0)` instances?
- [ ] Merge `DataOps` and `MLOps`?
- [ ] Remove `DivOps` (it's a conference)? Looks like a typo of DevOps
- [ ] Remove some other single-use labels? (list in https://github.com/iterative/dvc.org/issues/2340#issuecomment-810398961)
- [ ] Use more some other single-use labels?

UPDATE: Not doing those for now, but leaving here as a historic discussion in case we need to dig it up later.

### CODE REVIEW

**Comment by jendefig** [comment]
Sorry so late on this.  My github stuff goes to the 'Other' section of my personal email which I never have time to read anymore. Need to remedy this. 😬

 I guess I need some background here.  I'm used to working in Squarespace, where if I want to tag something, I just type it in and it's automatically added.  So in this case if there's something new, we have to make a special pull request to pre-populate the tags so I can have the tag in the blog post?
 
 What are functions of the tags in this case?  They are to find these instances in the site, right?  And if so, how is that done?  Not seeing search functionality on site except for in docs.

**Comment by rogermparent** [comment]
> I guess I need some background here. I'm used to working in Squarespace, where if I want to tag something, I just type it in and it's automatically added. So in this case if there's something new, we have to make a special pull request to pre-populate the tags so I can have the tag in the blog post?
>
> What are functions of the tags in this case? They are to find these instances in the site, right? And if so, how is that done? Not seeing search functionality on site except for in docs.
No worries! Here's a quick run-down:

- Our blog engine supports arbitrary parsed metadata in the "front-matter" of each blog post markdown file, such that they can be edited in plaintext in the same way the blog posts are. 
- Tags are supported through populating the `tags` field here, and then fed into Gatsby so the data can be queried and used throughout the website.
- We currently have [index pages for each tag](https://dvc.org/blog/tags/gems) that are accessible at the bottom of each blog post, but we currently no page that lists all the tags, though there are plans to fix that.
- This PR is a retroactive change, altering the tags across the whole repo to combine ones that are redundant (e.g. all posts with "Discord" and "Gems" tags now have the "Discord Gems" tag instead.

**Comment by jendefig** [comment]
> * This PR is a retroactive change, altering the tags across the whole repo to combine ones that are redundant (e.g. all posts with "Discord" and "Gems" tags now have the "Discord Gems" tag instead.

Maybe I'm not understanding but Discord and Gems are two different things.  Why would they be combined?  Community Gems comes from Discord, but there might be other instances that we are talking about Discord in the Blog and we just want to tag Discord. 

On the list above:
- I checked off DivOps
- From #2340 maybe 'completion' could go as well as "Udemy Course" because there is "Udemy"
- How would I add things as they come up?  For example, in this month's Heartbeat I could add "Made with ML" because there's some new lessons out.  This could repeat again. Or also Ai Singapore who has had two Tutorials out.

If I put it in the tag section of the blog post at we don't have a tag for it, what happens?

**Comment by shcheklein** [comment]
> If I put it in the tag section of the blog post and we don't have a tag for it, what happens?

I think it's totally fine to put any tags we want to put. Indeed it would be great to keep it more or less clean (reuse as much as we can), but we should be limiting it to a very precise subset of tags. E.g. `Made with ML` makes perfect sense to me, even if we have a single instance of it.

> but Discord and Gems are two different things.

agreed on this

> DivOps

is also fine to have it to my mind.

**Comment by jorgeorpinel** [comment]
> we currently have no page that lists all the tags, though there are plans to fix that

Yes, https://github.com/iterative/dvc.org/issues/2356 🙂 

> Discord and Gems are two different things.

@jendefig @shcheklein I combined them in this proposal because they seem to always be found together. I didn't think we were blogging about Discord nor about Gems, but rather about "Discord Gems" which is our own concept 💎

I did a quick check now and from the titles I couldn't find an article about Discord itself. Maybe a better tag is `support` or `community`? That could cover our chat (currently Discord but maybe something else in the future), the forum (Discuss), email (Google Groups), etc.

That all said Idk if this effort is worth it, this PR was meant as a small start / RFC.

p.s. I haven't removed DivOps

> How would I add things as they come up?
E.g. Made with ML makes perfect sense to me, even if we have a single instance of it.

Yep, go for it. I guess my main goal here is to decide whether we want some tagging guidelines at all. I also think it would be ideal to keep it more or less clean, but not sure there's any real impact/ priority on this.

**Comment by jendefig** [comment]
> I did a quick check now and from the titles I couldn't find an article about Discord itself. Maybe a better tag is `support` or `community`? That could cover our chat (currently Discord but maybe something else in the future), the forum (Discuss), email (Google Groups), etc.

Yes.  Let's definitely have a `Community` tag!  That's a logical solution.

**Comment by jendefig** [comment]
> I guess my main goal here is to decide whether we want some tagging guidelines at all. I also think it would be ideal to keep it more or less clean, but not sure there's any real impact from this (Ikd if our tags get much use).

So should we have a Tag limit per blog article?  So it forces us to decide on the most impactful content of any post and limit the superfluous tags?  Maybe 5 max?

**Comment by jorgeorpinel** [comment]
> Let's definitely have a Community tag!

Done.

> So should we have a Tag limit per blog article?

Not a hard limit. I'd just try to keep tags to a minimum: only use concepts that are really key to each publication. That would be my personal approach but it's probably best that you decide on some pseudo-policy (and maybe update https://dvc.org/doc/user-guide/contributing/blog ?) @jendefig @flippedcoder

**Comment by jorgeorpinel** [comment]
@jendefig @rogermparent please approve PR (if you approve) so we can merge it.

**Review by rogermparent — APPROVED** [review]
I think this looks good, particularly from the technical side, but I'm not an authority on the product side so somebody else who is may want to confirm.

**Comment by jorgeorpinel** [comment]
Thanks @rogermparent . Should be good to go, but since @shcheklein was involved here earlier, I'll try to get a confirmation from him.

**Pull request merged**
