### PR TITLE
Renamed --outs-only to --dvc-only

### PR DESCRIPTION
**Pull request by growupboron**
Changes pending to [iterative/dvc/pull/3797](https://github.com/iterative/dvc/pull/3797)

Fixes [iterative/dvc/issues/3589](https://github.com/iterative/dvc/issues/3589)

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please chose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Please request my review here if/when iterative/dvc/pull/3797 is merged. Thanks

**Comment by growupboron** [comment]
@jorgeorpinel the corresponding pr in the dvc got merged, can you please review the pr?

**Comment by jorgeorpinel** [comment]
Yup, thanks again for that core contribution. Reviewing...

> FYI an official way to request reviews on Github is on the top-right corner:
> image
> But np, a comment also works.

**Comment by jorgeorpinel** [comment]
Oops not sure I should've merged this yet though. Hopefully not a big deal... When can we expect iterative/dvc/pull/3797 released @efiop? Thanks

**Comment by shcheklein** [comment]
@jorgeorpinel not a big deal, it'll be released (or pre-released at least) soon

**Pull request merged**
