### PR TITLE
Use alphabetical order in `exp` API ref

### PR DESCRIPTION
**Pull request by daavoo**

### CODE REVIEW

**Review by dberenbaum — APPROVED** [review]

**Comment by jorgeorpinel** [comment]
Why do you guys prefer abc? Consistency?

Currently we have sub-commands sorted by relevance (except `exp` now). Should we update all the others?

**Comment by jorgeorpinel** [comment]
See https://dvc.org/doc/command-reference/metrics, https://dvc.org/doc/command-reference/plots, https://dvc.org/doc/command-reference/queue, and https://dvc.org/doc/command-reference/remote .

**Comment by dberenbaum** [comment]
Good point, @jorgeorpinel. I just saw it matched the CLI. No strong opinion on the order.

Let's not go through every command for consistency. Not enough value for the effort.

**Comment by daavoo** [comment]
> Why do you guys prefer abc? Consistency?
> Currently we have sub-commands sorted by relevance (except exp now). Should we update all the others?

I personally prefer ABC because is objective and easier for me to comprehend at first sight. 
Relevance is subjective and feels tricky to get right, who decides the ranking?

**Comment by daavoo** [comment]
> Let's not go through every command for consistency. Not enough value for the effort.

👍 I just sent the quick patch because `exp` has the most subcommand and it was becoming harder for me to navigate the sidebar

**Pull request merged**
