### PR TITLE
November Heartbeat

### PR DESCRIPTION
**Pull request by jendefig**
Here is the November Heartbeat.

The images have been through tiny.png twice. The team one is the biggest.  It's a jpeg.  

This should go out November 17.

Let me know if you take issue with any content.  I included Santiago's post about feature stores even though not related to DVC because he is a great community member and our community may be interested in the content.

### CODE REVIEW

**Comment by jendefig** [comment]
I have now gone back over this with fresh eyes.  I think I even got all the Oxford commas! Needs review from whoever can and merge. @jorgeorpinel @iesahin @shcheklein @casperdcl

**Comment by jendefig** [comment]
Not sure what the problem is with the links @julieg18 @rogermparent.  They all seem to work.

**Review by shcheklein — APPROVED** [review]
This looks great to me 👍 🎉 

Should we send an email update! You are preparing great blog posts, but I think we can share them in other ways

**Comment by jendefig** [comment]
> This looks great to me 👍 🎉
> 
> Should we send an email update! You are preparing great blog posts, but I think we can share them in other ways

Yes.  This was to be a part of the email for the release (at the bottom)... but the release got moved to the end of the month.... 🤔   We don't want two emails right?  I missed last month's email 😞 Too much going on.

**Pull request merged**
