### PR TITLE
March comm gems

### PR DESCRIPTION
**Pull request by jendefig**
This makes revisions to the question regarding keeping experiments in different repositories as well as moves the April Meetup info to the end.

### CODE REVIEW

**Comment by shcheklein** [comment]
Hmm ... something funny is happening with this PR? it has some old changes and is conflicting with master ...

**Comment by jendefig** [comment]
> Hmm ... something funny is happening with this PR? it has some old changes and is conflicting with master ...

Ok.  What do I need to do.  The changes look how I did them.  Is something else wrong?

**Comment by shcheklein** [comment]
I think you need to create a new PR, from a new branch. It seems that you were trying to keep iterating in the existing branch? But it is merged already, you now need to synchronize your master, do a new branch, do changes there, and create a new PR. That my take from from what I see, may be I'm missing something.

**Comment by jendefig** [comment]
Closing.  Re-did in new-march-comm-gems branch

**Pull request closed without merging**
