### PR TITLE
Flatten dvclive docs

### PR DESCRIPTION
**Pull request by dberenbaum**
Follow-up/alternative to #4421.

@daavoo What do you think about this restructure to get rid of one nesting level in the DVCLive docs? I wanted to do it on top of/instead of #4421 so we don't have to restructure and redirect twice.

Edit to summarize the changes:

Old structure:

Screenshot 2023-03-21 at 2 50 35 PM

New structure:

Screenshot 2023-03-21 at 2 50 43 PM

To make this work, I moved `/doc/dvclive/api-reference/index.md` to `/doc/dvclive/index.md`.

### CODE REVIEW

**Comment by daavoo** [comment]
> @daavoo What do you think about this restructure to get rid of one nesting level in the DVCLive docs?

I like it 👍 

> I wanted to do it on top of/instead of https://github.com/iterative/dvc.org/pull/4421 so we don't have to restructure and redirect twice.

😓

**Comment by dberenbaum** [comment]
@daavoo Not a huge deal if we merge this quickly on top, right? I think #4389 is a bigger pain now, but I can fix that when it's ready.

**Comment by daavoo** [comment]
> @daavoo Not a huge deal if we merge this quickly on top, right? I think #4389 is a bigger pain now, but I can fix that when it's ready.

wait. what would be the conflict redirect after this restructure?

**Review by daavoo — APPROVED** [review]
Is there anything blocking the merge @dberenbaum ?

**Comment by dberenbaum** [comment]
No, I'll merge now @daavoo. Thanks!

**Comment by daavoo** [comment]
I think this broke the automatic linking for `Live.method` syntax.

**Comment by daavoo** [comment]
> Do you have any idea how the automatic linking works?

https://github.com/iterative/gatsby-theme-iterative/blob/main/packages/gatsby-theme-iterative/plugins/gatsby-remark-dvc-linker/liveLinker.js

I think is easy fix but don't really know how the release process works so updates in that repo get propagated to `dvc.org`

**Pull request merged**
