### PR TITLE
Switching out references of Iterative Studio to DVC Studio

### PR DESCRIPTION
**Pull request by jendefig**
This swaps out all the Iterative Studio references in the Docs with DVC Studio to correct branding discrepancies.

Happy Hacktoberfest! 🎃

### CODE REVIEW

**Comment by dberenbaum** [comment]
@jendefig I think we also have a bunch of Studio mentions without Iterative/DVC. Do we want to change those also?

**Comment by jendefig** [comment]
> @jendefig I think we also have a bunch of Studio mentions without Iterative/DVC. Do we want to change those also?

Good point! Maybe.  As a company we have a bad habit of calling it Studio.  I think it's fair to say "Studio" in the rest of a paragraph as long as the first mention in every paragraph is "DVC Studio."  If all of them are DVC Studio it might be conversationally annoying.  An alternative would be to replace it with "the tool" in some places, but that feels awkward and not specific enough.

One question I had was regarding the "Studio access token" section [here](https://dvc.org/doc/studio/user-guide/account-and-billing#security-details).  I didn't change those references because I figured that would mean changes needed to be made in the platform.  Should we change to "DVC Studio access token" on the platform?  My feeling is yes, but that seems to open a can of worms more challenging than these changes in the docs so I left that one alone.

**Review by dberenbaum — APPROVED** [review]

**Comment by tapadipti** [comment]
Thanks @jendefig for making these changes.
I've added a commit with changes in 2 more places.

> One question I had was regarding the "Studio access token" section

In the Studio user profile page, this field is called `Studio Access Token`. For DVC/DVCLive, it's called `studio.token` and `DVC_STUDIO_TOKEN`. Considering all this, I'd suggest not changing it in the docs for now. At some point, it would be good to sync the names.

@iterative/platform It looks like the only remaining part is the `Self Hosting` docs pages. These pages extensively use the name Studio (and not Iterative Studio, unlike the rest of the docs). Is it okay to replace the name  `Studio` with `DVC Studio` in these pages or could it cause confusion to users (such as if the images are called "Studio" images)?

**Comment by tapadipti** [comment]
@jendefig For the test failures, merging [this PR](https://github.com/iterative/dvc.org/pull/4912) should resolve it.

**Comment by jendefig** [comment]
> . Considering all this, I'd suggest not changing it in the docs for now. At some point, it would be good to sync the names.

Ok. Makes sense! 👍

**Comment by jendefig** [comment]
> @iterative/platform It looks like the only remaining part is the `Self Hosting` docs pages. These pages extensively use the name Studio (and not Iterative Studio, unlike the rest of the docs). Is it okay to replace the name `Studio` with `DVC Studio` in these pages or could it cause confusion to users (such as if the images are called "Studio" images)?

Oh.  I see what you mean.  I didn't find these because I searched for "Iterative Studio" to find the other.  Yes, absolutely these should be changed.  No one will ever find this content through a search with the headers this way.  There are way to many things in our industry alone named Studio (Azure ML Studio, Label Studio, Sagemaker studio,...) let alone the rest of the world to ever find this content.  Self-hosting Studio could be a ballet studio that gives members access any time they want.  We need to have the brand tied into all of this.

**Comment by dberenbaum** [comment]
> In the Studio user profile page, this field is called `Studio Access Token`. For DVC/DVCLive, it's called `studio.token` and `DVC_STUDIO_TOKEN`. Considering all this, I'd suggest not changing it in the docs for now. At some point, it would be good to sync the names.

This was actually intentional. I believe all DVC [environment variables](https://github.com/iterative/dvc/blob/main/dvc/env.py) start with `DVC_` (since environment variables are global to the environment) and [config options](https://dvc.org/doc/user-guide/project-structure/configuration) do not (since they are already inside DVC-specific config files). This is a common practice (for example, you can use env var `AWS_PROFILE` or use `profile` inside `~/.aws/config`).

**Comment by jesper7** [comment]
> https://github.com/orgs/iterative/teams/platform It looks like the only remaining part is the Self Hosting docs pages. These pages extensively use the name Studio (and not Iterative Studio, unlike the rest of the docs). Is it okay to replace the name Studio with DVC Studio in these pages or could it cause confusion to users (such as if the images are called "Studio" images)?

Yes, totally. Feel free to swap them out as part of this PR :+1:

**Comment by jendefig** [comment]
> > Yes, totally. Feel free to swap them out as part of this PR 👍
> 
> @jendefig Do you want to add this here or should we leave it out?
> 
> @tapadipti Is there anything else you feel needs to be updated in the PR?

I've had to prioritize conference things.  I will run a search on "Studio" and do those corrections in  the next couple days.

**Comment by tapadipti** [comment]
@jendefig merged the restyling changes, resolved conflicts, and created a [new PR on top of this one](https://github.com/iterative/dvc.org/pull/4944). This new PR should address your comment `I will run a search on "Studio" and do those corrections in the next couple days.` I've requested your review on that PR.

**Review by jendefig — COMMENTED** [review]
🙏

**Pull request merged**
