### PR TITLE
Adding Get started CML  Gitlab instructions

### PR DESCRIPTION
**Pull request by jendefig**
Submitting the Getting Stared with CML on GitLab Instructions for review.  

Take a look at images and let me know if they are ok.  Some of the images have bounding boxes for clarity.  Let me know if any of the others should too.

Also there isn't navigation for this page.  I talked to Jorge last week about this.  We will need two:
"Get Started with CML on Github/lab"

### CODE REVIEW

**Comment by shcheklein** [comment]
hmm, it looks like pre-commit hook is still not set, CI fails ^^ ... it should be running when you do a commit.

**Comment by jendefig** [comment]
@shcheklein Sorry, I'm lost.  What do I need to do and where?  I had an error the first time I tried to commit and then the second time it worked.  Is that why?

**Comment by shcheklein** [comment]
@jendefig no worries! let's try to figure out together what's going on here. could you please share some screenshots, what error do you have and what exactly did you do to make this PR. If possible. That would help to see what's going on here.

**Comment by jendefig** [comment]
@shcheklein  
image

**Comment by shcheklein** [comment]
@jendefig I think you need to run the same `git commit` second time (what you see on your screenshot is that it fixed up the file, but failed (instead of making a commit)- to let you decide to do commit now, review, etc). In most cases that is the workflow that is expected:


```
√ docs/cml % git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   get-started-with-cml-on-gitlab.md

----------------------

√ docs/cml % git commit -a -m "test"
husky > pre-commit (node v15.0.1)
$ pretty-quick --staged --no-restage --bail
🔍  Finding changed files since git revision 118858c9.
🎯  Found 1 changed file.
✍️  Fixing up content/docs/cml/get-started-with-cml-on-gitlab.md.
✗ File had to be prettified and prettyQuick was set to bail mode.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky > pre-commit hook failed (add --no-verify to bypass)

----------------------

√ docs/cml % git commit -a -m "test"
husky > pre-commit (node v15.0.1)
$ pretty-quick --staged --no-restage --bail
🔍  Finding changed files since git revision 118858c9.
🎯  Found 1 changed file.
✅  Everything is awesome!
$ /Users/ivan/Projects/dvc.org/node_modules/.bin/lint-staged
ℹ No staged files match any configured task.
[master 6145a7c5] test
 1 file changed, 109 insertions(+)
 create mode 100644 content/docs/cml/get-started-with-cml-on-gitlab.md
 ```

**Comment by jendefig** [comment]
So trying again yielded: - 
image

**Comment by jendefig** [comment]
This is my status.  Could it be happening because I haven't pushed up these images? (duh!) And I don't know what package-lock.json is.  
image

**Pull request closed without merging**
