### PR TITLE
guide: link to sample checkpoints repo from Exps

### PR DESCRIPTION
**Pull request by jorgeorpinel**
per https://github.com/iterative/dvc.org/issues/2292#issuecomment-816849304

### CODE REVIEW

**Comment by dberenbaum** [comment]
I'll come back to this one after we've cleaned up the PRs and comments in https://github.com/iterative/dvc-checkpoints-mnist, and maybe let's see where #2373 fits at least (although we don't have to wait for it to be complete).

**Comment by jorgeorpinel** [comment]
OK no rush I guess. But I thought we agreed this was a good first step? 🙂

**Comment by dberenbaum** [comment]
Yeah, you are right. We don't have to wait on #2373. Let me take another look at the PRs in https://github.com/iterative/dvc-checkpoints-mnist next week and see if they can be quickly addressed, and then we can merge this.

**Review by dberenbaum — APPROVED** [review]
Sorry, missed that this was waiting for review.

**Comment by jorgeorpinel** [comment]
No worries.

**Pull request merged**
