### PR TITLE
adjusted tabs to code and changed name to match cml website

### PR DESCRIPTION
**Pull request by jendefig**
> You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by shcheklein** [comment]
@jendefig looks good to me! please, ping Elle (suggest a review) at the top right corner. If she approves you will be able to merge on your own (I'll add you to the team).

**Comment by jendefig** [comment]
> @jendefig looks good to me! please, ping Elle (suggest a review) at the top right corner. If she approves you will be able to merge on your own (I'll add you to the team).

@elleobrien Can you check this to see if I did it right?

**Comment by elleobrien** [comment]
@shcheklein can you make a deployment? don't see it

**Review by elleobrien — APPROVED** [review]

**Comment by shcheklein** [comment]
@jendefig @elleobrien I think you should be able to Squash and merge now:

Screen Shot 2021-02-02 at 12 21 11 PM


it will be deployed automatically after that.

**Pull request merged**
