### PR TITLE
Updated exp diff tables

### PR DESCRIPTION
**Pull request by daavoo**
P.R. for https://github.com/iterative/dvc/pull/6888

### CODE REVIEW

**Review by dberenbaum — CHANGES_REQUESTED** [review]
In the synopsis section of the cmd ref, `--old` is still shown as an option.

Also, where are the related core/docs PRs for `metrics diff --old`?

**Comment by daavoo** [comment]
> Also, where are the related core/docs PRs for `metrics diff --old`?

There is not such an option for `dvc metrics diff` (And, afaik, it has never existed). It looks like the docs are not in sync with the command

**Review by dberenbaum — APPROVED** [review]

**Comment by jorgeorpinel** [comment]
> There is not such an option

It must have existed when @iesahin wrote this. Anyway, thanks for the update!

**Comment by iesahin** [comment]
FYI `--old` joined to `dvc metrics diff` options in https://github.com/iterative/dvc.org/pull/1360/files

@daavoo @jorgeorpinel

**Comment by jorgeorpinel** [comment]
Now, that's --old.

**Pull request merged**
