### PR TITLE
[tmp] Run cache (1.0)

### PR DESCRIPTION
**Pull request by jorgeorpinel**
> You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Cc @efiop if you're not started feel free to contribute to this branch.

**Comment by shcheklein** [comment]
@jorgeorpinel let's move this to the run cache ticket that we agreed DVC core team handles first. And close this PR since it creates confusion.

**Comment by jorgeorpinel** [comment]
I'm not involved in the run cache issue, can someone point me to it? Closing this one.

**Comment by efiop** [comment]
> I'm not involved in the run cache issue, can someone point me to it? Closing this one.

@jorgeorpinel https://github.com/iterative/dvc.org/issues/1289

**Comment by jorgeorpinel** [comment]
Ty. Looks like I was involved after all 😋

**Pull request closed without merging**
