### PR TITLE
Add GTO docs link to sidebar

### PR DESCRIPTION
**Pull request by aguschin**

### CODE REVIEW

**Review by jorgeorpinel — CHANGES_REQUESTED** [review]
OK. But why? Is it not good enough to have it in mlem.ai/doc/gto ? Seems much closer to MLEM. Counter-example: we don't have an external nav link to Studio docs from mlem.ai/doc

No strong opinion. The only issue is that both sites look very similar and if you click on this you may not realized you've gone from DVC to MLEM docs and then get lost.

**Review by jorgeorpinel — APPROVED** [review]
> I meant to approve with that comment.

**Comment by jorgeorpinel** [comment]
Oh shoot. I guess this has auto-merge on... Well, we can roll back if needed. WDYT @aguschin @shcheklein @dberenbaum ?

**Comment by aguschin** [comment]
@jorgeorpinel, sorry, I turned on auto-merging 😅 

Since GTO is something that is useful for DVC users, I thought it would be good to have a link to GTO docs. But, having links from `use-cases/model-registry` and some Studio docs pages may be enough. Having a link in a sidebar is just more visible. No strong opinion.

**Comment by jorgeorpinel** [comment]
> GTO is something that is useful for DVC users

Why or how is it especially useful for them? TBH for now I'd incline to remove the link per https://github.com/iterative/dvc.org/pull/4131#pullrequestreview-1193819256. We do mention GTO in some DVC docs, let's just link to the docs instead of the repo in those places?

**Pull request merged**
