### PR TITLE
remote WebDav: Add docs

### PR DESCRIPTION
**Pull request by shizacat**
This is add-ons for remote webdav

### CODE REVIEW

**Comment by shcheklein** [comment]
@jorgeorpinel merged prematurely into master, please TAL and fix directly. Some small adjustments are needed here.

**Comment by shcheklein** [comment]
@shizacat thanks for the docs! Closing this, the one created by Restyled is already merged.

**Comment by jorgeorpinel** [comment]
> merged prematurely into master, please TAL and fix directly

I just noticed this @shcheklein. I'm not able to find `webdav` in the core repo. Is this a released feature yet? I'm fixing it here BTW: #1356

**Comment by jorgeorpinel** [comment]
UPDATE: I'm removing all of this per #1355.

**Pull request closed without merging**
