### PR TITLE
updates to community page

### PR DESCRIPTION
**Pull request by jendefig**
Updates to Community page
- numbers
- UGC
- Events
New images have gone through tiny.png

### CODE REVIEW

**Comment by jendefig** [comment]
Something weird is happening.  The dates are showing up a day earlier than how I entered them in.  @shcheklein @rogermparent @julieg18 
image
image

**Comment by julieg18** [comment]
> Something weird is happening. The dates are showing up a day earlier than how I entered them in. 

It's working for me locally, but not the deployed site... Is it working correclty on your local computer @jendefig?

**Comment by jendefig** [comment]
> It's working for me locally, but not the deployed site... Is it working correctly on your local computer @jendefig?

Yes.  It's working for me locally too, except the October Heartbeat image isn't coming through.  But I guess it's okay.  🤷‍♀️

**Comment by julieg18** [comment]
Looks like it's an issue on how we convert our strings into dates. Though I'm not sure why it's only showing while deployed. I'll open a pull request for fixing it.

**Comment by jendefig** [comment]
> I'll open a pull request for fixing it.

So does that mean this can't be merged until it's fixed?  Or it's just a weird thing with Heroku and this will be fine when merged? @julieg18

**Comment by julieg18** [comment]
> > I'll open a pull request for fixing it.
> 
> 
> 
> So does that mean this can't be merged until it's fixed?  Or it's just a weird thing with Heroku and this will be fine when merged? @julieg18 

The dates will stay incorrect until my fix pull request is merged into master.

**Review by shcheklein — APPROVED** [review]

**Pull request merged**
