### PR TITLE
docs: update params diff table

### PR DESCRIPTION
**Pull request by efiop**
Per https://github.com/iterative/dvc/pull/4655

> You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by shcheklein** [comment]
@rogermparent any ideas what's happening with CI in this case?

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
@efiop should we update `params/index.md` ?

also I see None is mentioned in descriptions?

**Review by shcheklein — CHANGES_REQUESTED** [review]
See a comment above ^^

**Comment by efiop** [comment]
Oops, forgot that there is duplication there. Adjusted. Thank you! :pray:

**Review by shcheklein — APPROVED** [review]

**Pull request merged**
