### PR TITLE
redirect: from removed UC to GS section

### PR DESCRIPTION
**Pull request by jorgeorpinel**
per https://github.com/iterative/dvc.org/pull/3275#issuecomment-1041896835

- [x] & Fix broken links

---

- [ ] Reindex [from Search Console](https://search.google.com/search-console/inspect?resource_id=sc-domain%3Advc.org&id=hnJIcvyJpSSFOhUFO7YXIw) when merged.

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Hello again @julieg18 👋🏼  . The [failing check](https://app.circleci.com/pipelines/github/iterative/dvc.org/12721/workflows/9aae9667-791d-43dd-bf63-955de8c00d7a/jobs/12780) in here is having the same problem as in https://github.com/iterative/dvc.org/pull/3313#pullrequestreview-897852863. I'm afraid this will happen in every PR going fwd since all PRs try to format the entire code base (I think). So we should def. figure out how to avoid Prettier from trying to format that one line, or some other solution. Thanks. Cc @rogermparent

**Review by shcheklein — APPROVED** [review]

**Comment by casperdcl** [comment]
Should we track these things in https://github.com/iterative/link-check/issues?

**Comment by jorgeorpinel** [comment]
That's not related to the link checker.

**Comment by jorgeorpinel** [comment]
But I guess [this check](https://github.com/iterative/dvc.org/pull/3275/checks) not catching all the broken links (fixed in this PR) may be...

**Comment by julieg18** [comment]
> Hello again @julieg18 👋🏼 . The [failing check](https://app.circleci.com/pipelines/github/iterative/dvc.org/12721/workflows/9aae9667-791d-43dd-bf63-955de8c00d7a/jobs/12780) in here is having the same problem as in [#3313 (review)](https://github.com/iterative/dvc.org/pull/3313#pullrequestreview-897852863). I'm afraid this will happen in every PR going fwd since all PRs try to format the entire code base (I think). So we should def. figure out how to avoid Prettier from trying to format that one line, or some other solution. Thanks. Cc @rogermparent 

Pushed a fix (#3330)! Added a `prettier-ignore` comment to stop prettier from formatting the line.

**Pull request merged**
