### PR TITLE
guide: link to remote storage types in link

### PR DESCRIPTION
**Pull request by jorgeorpinel**
Just a batch replace of links to the new Remote Storage page (Supported Types section) introduced in https://github.com/iterative/dvc.org/pull/4264.

- [ ] Do not merge before parent PR, https://github.com/iterative/dvc.org/pull/4264

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Hi @dberenbaum . Please note this is basically part of #4284. I've solved the conflicts so it should be mergeable. Thanks

**Comment by jorgeorpinel** [comment]
\* I meant https://github.com/iterative/dvc.org/pull/4264

**Review by dberenbaum — APPROVED** [review]

**Comment by dberenbaum** [comment]
Thanks again @jorgeorpinel!

**Comment by jorgeorpinel** [comment]
On the contrary, thanks for helping get these merged!

**Pull request merged**
