### PR TITLE
update list of supported dvc remote types

### PR DESCRIPTION
**Pull request by torresalyssa**
update the list of supported dvc remote types in `managing-external-data.md` to match `importing-external-data.md`

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Ah. Thanks @torresalyssa but the remotes supported for [external dependencies](https://dvc.org/doc/user-guide/data-management/importing-external-data) are different than the ones for [external outputs](https://dvc.org/doc/user-guide/data-management/managing-external-data), actually. For a full list of DVC remotes please refer to https://dvc.org/doc/command-reference/remote/add#supported-storage-types for now. See also https://github.com/iterative/dvc.org/issues/2866

**Comment by torresalyssa** [comment]
Thanks that is helpful to know, I wasn’t aware they were different!

**Comment by jorgeorpinel** [comment]
These docs are a bit old though. @dberenbaum can you please confirm this is still the case? Thanks

**Comment by dberenbaum** [comment]
Yup, I think that's still correct. Thanks anyway for the PR!

**Pull request closed without merging**
