### PR TITLE
community page updates

### PR DESCRIPTION
**Pull request by jendefig**
Updates to user content and another event.  Waiting for Ingamul to redo header desktop and mobile graphics to say instead: "Could you be our next Developer Advocate?"  If that's agreeable. 🙂

### CODE REVIEW

**Comment by shcheklein** [comment]
Looks great!

Do we need to wait for the new image to merge?

Also some suggestions:

```
1800+
registered developers
50K+
```

should we update these numbers ^^

Can we do a different image for meetups (June vs July)?

**Comment by shcheklein** [comment]
> Waiting for Ingamul to redo header desktop and mobile graphics to say instead: "Could you be our next Developer Advocate?" If that's agreeable.

💯

**Comment by jendefig** [comment]
> Looks great!
> 
> Do we need to wait for the new image to merge?
> 
> Also some suggestions:
> 
> ```
> 1800+
> registered developers
> 50K+
> ```
> 
> should we update these numbers ^^
> 
> Can we do a different image for meetups (June vs July)?

I updated numbers.  Not sure how the 50K was arrived at.  This number that I put was messages SENT per Discord.  Not total messages.  Even if I add Discuss for the last month, it's just 97 more.  but that may be a good thing?  We are getting more succinct at answering in support and our docs are excellent enough to reduce need for messages?  We may want to put a different metric in that place?  Issues solved?  (How to quantify?) Contributors?  GH Stars for DVC and CML?  Also it says "developers."  It seems clear that not all are developers, but users may be more accurate?

On changing the pics.  I say no if that's ok.  I will be adding an event: DVC Learn on July 14th.  (Still need to create graphic; DeeVee with just glasses, not sunglasses is the idea).  Another type of Meetup for our kicking the tires/learning audience.  The idea is to help people learn with DVC Learn and then they "graduate" to Office Hours.  Milecia will be doing these.  Just half hours.  So those graphics will look different, but this way people will be able to delineate over time the types of events visually.  Also Milecia is waiting to hear back from another Conference she is likely doing in July.  So that will be a different graphic.  How many fit here?  I haven't seen it all filled in. @rogermparent 

On the header image(s) - Let's wait a tad.  He was asleep during my request.  If it arrives tomorrow morning and we can resolve the metrics issue, we can wrap up all of this mañana.  LMK about what you think on metrics.

**Comment by shcheklein** [comment]
> Not sure how the 50K was arrived at.

Probably from the statsbot: `1,825 Days: 52,652 messages` (and I'm not sure it's everything or from the point we started using the bot - we can confirm in the UI for the statsbot and approximate to the total number if we really want to go precise).

> Contributors? GH Stars for DVC and CML? 

They are not very informative unfortunately in terms of community. Contributors - hard to count since they spread across different repos and overlap, stars - not about community.

> Also it says "developers." It seems clear that not all are developers, but users may be more accurate?

Good point ... may be even members?

> On changing the pics. I say no if that's ok

Absolutely :) And thank for the explanation!

Sounds good on everything else!

**Comment by shcheklein** [comment]
Looks like Dev Advocate image is too low res

**Comment by jendefig** [comment]
> Looks like Dev Advocate image is too low res

Corrected this.  Should be ok now.

**Comment by jendefig** [comment]
> Good point ... may be even members?

I still need to figure out how to change this...

**Comment by shcheklein** [comment]
Should we fix the numbers (13K, etc)?

To find where the text is defined in the repo, try to do `git grep "developers"` or even `git grep "registered developers"`

**Comment by jendefig** [comment]
> Probably from the statsbot: `1,825 Days: 52,652 messages` (and I'm not sure it's everything or from the point we started using the bot - we can confirm in the UI for the statsbot and approximate to the total number if we really want to go precise).

The wording says monthly messages on the site.  Do we want monthly or all time messages?  One or the other needs to change.  I think monthly makes more sense, but the stats bot does not give that number.  I need to research how to get that.  It would be a good thing to track.  But what we are tracking is support.  The value of this number is odd because it will forever be fighting itself.  We would want support calls to go down, but we want users to grow.  I need to think about this more.  Maybe we should have something all together different there.  

And also where do I adjust the wording on that page.  I'm not finding in community.json or the index for community?

**Comment by jendefig** [comment]
Ok. @shcheklein I think this is good to go now.  I took an average of the last 3 months of messages on the Discord server.  That seemed logical.  The user content is updated as well as the events. Pics have been run through tiny.png. 👍

**Comment by jendefig** [comment]
Noticed though on DVC Blog portion of the Community page - this auto populates right @rogermparent ?  Why is the Community Gems post not first in line?  Does it wait a day or something before it updates?

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
Thanks @jendefig ! Great update.

**Pull request merged**
