### PR TITLE
More swap names

### PR DESCRIPTION
**Pull request by tapadipti**
More name swaps on top of [Jeny's PR](https://github.com/iterative/dvc.org/pull/4911).

### CODE REVIEW

**Review by jendefig — COMMENTED** [review]
This is beautiful! 😍 Thanks @tapadipti for doing this!  It's been a bit of a crazy week for me. 😅  

I'm a bit confused though.  This includes what was in the other one, right?  Not just that part that wasn't done? I squashed and merged the other one.  So a bunch of this may be done already.  But I see the ones I missed from the plain "Studio" search and it's beautiful!

Also QQ: how big a deal is it to change the swoosh Studio icon in the corner of the platform to the DVC logo instead?

**Comment by tapadipti** [comment]
> This includes what was in the other one, right?  Not just that part that wasn't done? I squashed and merged the other one.  So a bunch of this may be done already. 

@jendefig This PR was built on top of your earlier one. It was supposed to be merged into your branch before that PR was merged. But it's ok - you can review and merge this PR separately now. I've resolved conflicts with main and the duplicate changes shouldn't be there now.




> how big a deal is it to change the swoosh Studio icon in the corner of the platform to the DVC logo instead?

Do you mean in studio.iterative.ai or in the docs? And will we remove the use of the separate Studio logo from all places (docs, website, presentations, etc.)?

**Comment by tapadipti** [comment]
@jendefig Let me know if you have any questions/comments in this PR.

**Review by jendefig — APPROVED** [review]

**Comment by jendefig** [comment]
> Do you mean in studio.iterative.ai or in the docs? And will we remove the use of the separate Studio logo from all places (docs, website, presentations, etc.)?

I don't think we have had a complete decision on this because no one has time to pay attention to marketing atm. 😅  It's been mentioned in All Hands or slack.  But the swoosh brings zero brand recognition and is counterproductive to putting DVC Studio under the DVC ecosystem umbrella. It's just unnecessary. 

I would say it should change everywhere, ultimately. I recently had it changed for the flyer and look how nice it looks!
image

But if it's easy to change, I'd say to change it in the actual platform so that all videos going forward have the proper branding and our customers are seeing the right thing when they are in there.  Correcting all the image/video instances of it in the docs will be another project, that I imagine will take some time to accomplish. The longer we wait to make the change, the more content we will need to correct and further confusion will ensue.

**Pull request merged**
