### PR TITLE
fix(deps): Update deps and fix security vuln in sharp

### PR DESCRIPTION
**Pull request by natikgadzhi**
## Summary

This PR fixes the annoying warning from dependabot about `sharp`. Mostly minor version bumps.

I've checked that the site runs, but I did not compare `public` dir on this branch to `public` on main with full rebuild — I can do that if needed.

Pushing up a PR to spin up a full build on the review app and make sure that I haven't missed anything locally.

### CODE REVIEW

**Comment by shcheklein** [comment]
@yathomasi looks we need to fix some linter issue?

**Comment by natikgadzhi** [comment]
```
~/src/iterative/dvc.org main ?2 ❯ prettier -c src/gatsby/models/prune-cache/index.js                                                                                                                                                      
Checking formatting...
All matched files use Prettier code style!
~/src/iterative/dvc.org main ?2 ❯
```

Yup, looks weird.

**Comment by natikgadzhi** [comment]
Oh wait, I think @yathomasi already got the deps covered in #5001.

**Comment by yathomasi** [comment]
> Oh wait, I think @yathomasi already got the deps covered in #5001.

Yes, feel free to give an approval. @natikgadzhi @shcheklein

**Comment by yathomasi** [comment]
Thanks @natikgadzhi. Closing this PR as https://github.com/iterative/dvc.org/pull/5001 already got merged.

**Pull request closed without merging**
