### PR TITLE
Get Started: Next level

### PR DESCRIPTION
**Pull request by jorgeorpinel**
- [x] Change PR target to `master` when #1382 is merged.
- ~~It's called "Getting Started" for now because of #1406 but either that gets fixed or I just remove the tutorials/get-started and rename this new one eventually.~~

> You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
WDYT of the new intro so far @shcheklein ?

See https://dvc-landing-get-started-lnjjgt.herokuapp.com/doc/getting-started

**Comment by jorgeorpinel** [comment]
>  It's called "Getting Started" for now because of #1406 but either that gets fixed or I just remove the tutorials/get-started and rename this new one eventually.

Actually this may be tricky because we also have a 301 redirect now from `^/doc/get-started(/.*)?` to `/doc/tutorials/get-started$1` 🙁 so should we keep the "Getting Started" name for the new new version, @shcheklein ?

**Comment by shcheklein** [comment]
I don't understand the problem to be honest - we just move it outside and that's it. Change redirects if needed. Let's not spend time on "Next get started" at all for now as agreed.

Until I merge changes to the existing one with example get started migrated to DVC 1.0.

**Comment by jorgeorpinel** [comment]
Sure, I'm not working on this. I was doing the new DVC files&dirs guide: I added a redirect for it, and realized we have the old Get Started redirect, so I wanted to leave a comment here for future reference.

> I don't understand the problem ... Change redirects if needed

Not easy to change a 301 redirect: browsers that have visited it before cache it for an undefined length of time 😕

**Comment by jorgeorpinel** [comment]
Closing as stale for now.

**Pull request closed without merging**
