### PR TITLE
Remove all exps (2)

### PR DESCRIPTION
**Pull request by karajan1001**
Remaining issues from https://github.com/iterative/dvc.org/pull/2722

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Thanks! What about https://github.com/iterative/dvc.org/pull/2715#pullrequestreview-737875800, could we include that here too? 🙂

**Comment by jorgeorpinel** [comment]
OK @karajan1001 thanks. So you'll be adding an **Example: remove all experiments** example in this PR?

**Comment by karajan1001** [comment]
> OK @karajan1001 thanks. So you'll be adding an **Example: remove all experiments** example in this PR?

Sorry not quite understand what do you mean.  In #2722 we already have
```
$ dvc exp remove -A
$ dvc exp list
```
Is this an Example: remove all experiments

**Comment by jorgeorpinel** [comment]
@karajan1001 as explained in https://github.com/iterative/dvc.org/pull/2715#pullrequestreview-737875800 were just missing an example of `exp remove --queue`. I think it should be combined with the `exp remove -A` into a separate example instead of just adding to the generic **Examples** section. But feel free to use another PR, I'm merging this one so we move on 🙂

**Review by jorgeorpinel — APPROVED** [review]

**Comment by jorgeorpinel** [comment]
p.s. we will have an example in https://github.com/iterative/dvc.org/pull/2631 now that I think about it so adding one here too is less important. Up to you @karajan1001 (what do you think @iesahin ?)

**Pull request merged**
