### PR TITLE
added stage and frozen dependency concepts. modified others.

### PR DESCRIPTION
**Pull request by iesahin**
> You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by shcheklein** [comment]
@iesahin looks like CI fails (have you seen https://dvc.org/doc/user-guide/contributing/docs by chance?), could you please setup the dev env locally? 

@jorgeorpinel what is the status of the `iterative:ug-basic-concepts`, is it okay to do changes on top? Should we give @iesahin access to do commits on top of it and do a draft PR that will be deployed, etc?

**Comment by jorgeorpinel** [comment]
`ug-basic-concepts` is an archived branch to copy material from manually. It needed to be broken up and at this point the merge conflicts may be too much. That PR also has several relevant notes that should be taken into consideration, I think.

> In any case write access to the upstream is always nice so we can take it over later if needed without having to add another remote, etc.

**Comment by jorgeorpinel** [comment]
Oh. I see this PR goes into `g-basic-concepts`. Yeah I'm not sure that's a great idea for the reasons above. I'd make a new branch off master and copy certain parts, then work on them. But if you decide otherwise, maybe merge master into `g-basic-concepts` first? @iesahin would probably need help on that though (lmk).

**Comment by jorgeorpinel** [comment]
I also see this PR focuses on the basic concepts texts, that's good but maybe too many at once? I'd even try one or tow first, then we can review it rapidly, and then add more. At the end we can worry about the sidebar and possibly index of the section. Up to you Ivan, just thinking out loud here.

**Comment by shcheklein** [comment]
@iesahin I've added you to the repo, you can now create a branch and do PR from a branch (it's better since it will deploy itself). Let's consolidate this one, that previous branch, and do a new one. I also agree that it's probably better to do 1-3 at a time otherwise can be quite hard to review.

@jorgeorpinel thanks!

**Comment by shcheklein** [comment]
Closed in favor of https://github.com/iterative/dvc.org/commit/b5eaa630b445bdaa56753eb7c119a1d04d0f490d

**Pull request closed without merging**
