### PR TITLE
fix links plus a couple other things

### PR DESCRIPTION
**Pull request by jendefig**
A couple more bad links and corrected some things that should have been there the first time.  Sorry.  🤦‍♀️ My attempt to speed up my process on the front end, failed on the backend.

### CODE REVIEW

**Comment by jendefig** [comment]
@rogermparent So I guess the link checker has been turned off?  I missed a ton of bad links this month. Sorry I didn't realize it was being skipped, I should have noticed that.  Is this on purpose?

**Review by rogermparent — APPROVED** [review]

**Comment by rogermparent** [comment]
I'm not sure what exactly happened on the original PR since it's possible it could've run late or something, but looking at it I can see [a failed link checker report](https://github.com/iterative/dvc.org/runs/5233845167) attached to it

**Review by iesahin — APPROVED** [review]
Thank you @jendefig

**Comment by jendefig** [comment]
Thanks @rogermparent Missed that the first time. Those are the ones, except Medium. But that wouldn't have picked up the [Raymond Gasper]() which just sent back to the same blog post.  Is this how it should be?

**Comment by rogermparent** [comment]
It not picking up the empty link isn't a deliberate decision, but implicit on the link checker being designed to look for whole links and check for ones with abnormal responses. A lot of edge cases like empty links weren't taken into consideration, but it's something we should probably think about in the planned link check overhaul.

**Comment by jendefig** [comment]
Thanks @rogermparent!  It was totally my bad to miss putting them in. When I write, to go back and forth collecting links just slows me down, so I tried just typing [name]() and kept going to fill in links later, but missed those.  A simple cmd + f - () would find them for me though.  Just need to add to my process.

**Pull request merged**
