### PR TITLE
Add Testimonial Section

### LINKED ISSUE #2673: Integrating Testimonial.to into the website
I would like to integrate https://testimonial.to/features into the website?

**What is it***
A way for us to have a "wall of love" with video, text and tweeted testimonials on our website.  

**Things to Consider**
1. Where?  Landing page at bottom with direct to Community page? or Community page? or page of its own?
2. This should probably be on the Iterative site and maybe CML too?

@rogermparent @julieg18 Here is how the integration works with React: https://support.testimonial.to/integration-react

Let's discuss and get going! 😊

### PR DESCRIPTION
**Pull request by rogermparent**
Fixes #2673

### CODE REVIEW

**Comment by jendefig** [comment]
Cool!  But it's kind of gappy here.  Is there a way to fix that? 
image

**Comment by julieg18** [comment]
> Cool! But it's kind of gappy here. Is there a way to fix that?

I adjusted the section. The margin should match the other sections now.

**Comment by jendefig** [comment]
> > Cool! But it's kind of gappy here. Is there a way to fix that?
> 
> I adjusted the section. The margin should match the other sections now!

It still seems like the distance between the top image and the Testimonials text is more that the distance between the Community Image and the Contribute section.  It may be an optical illusion because the top image has white space where it aligns with the Testimonial Header. 
image
image
Actually I just measured it and it's definitely more.  I don't know anything about this stuff but could it be something with padding around the top image?

**Comment by julieg18** [comment]
> It still seems like the distance between the top image and the Testimonials text is more that the distance between the Community Image and the Contribute section.

You are correct! There is more space on the first section, but I believe it's also the same on dvc.org:
image
image

But if you'd like that space to be decreased to 50px (currently it's at 70px), I can open a separate pull request for decreasing it :)

**Comment by jendefig** [comment]
> But if you'd like that space to be decreased to 50px (currently it's at 70px), I can open a separate pull request for decreasing it :)

Oh.  Yes!  I see.  Yes.  Let's reduce to 50 px to tighten that up.  Then I think we will be good to go! 🔥

**Comment by jendefig** [comment]
Yay!  🎉  Thanks @julieg18 and @rogermparent Can we merge this?

**Comment by julieg18** [comment]
> Yay! 🎉 Thanks @julieg18 and @rogermparent Can we merge this?

I'd like to add a "testimonial" link in the nav bar. Maybe we also should consider moving the Testimonial section below the Community section? Besides that though, if we think this is good enough for a first iteration, we should be able to merge :)

**Comment by jendefig** [comment]
> > Yay! 🎉 Thanks @julieg18 and @rogermparent Can we merge this?
> 
> I'd like to add a "testimonial" link in the nav bar. Maybe we also should consider moving the Testimonial section below the Community section? Besides that though, if we think this is good enough for a first iteration, we should be able to merge :)

I'd love to see it in the Nav bar too and if it was in the Nav bar, I would be good with it being under the Community section.  I am writing Heartbeat to go out Wednesday and would like to point it out there if it's up.  Would you be able to do the Nav bar changes before then?  If not, then let's do this iteration and we will follow up with the other after the new year.

**Comment by julieg18** [comment]
> > > Yay! 🎉 Thanks @julieg18 and @rogermparent Can we merge this?
> 
> > 
> 
> > I'd like to add a "testimonial" link in the nav bar. Maybe we also should consider moving the Testimonial section below the Community section? Besides that though, if we think this is good enough for a first iteration, we should be able to merge :)
> 
> 
> 
> I'd love to see it in the Nav bar too and if it was in the Nav bar, I would be good with it being under the Community section.  I am writing Heartbeat to go out Wednesday and would like to point it out there if it's up.  Would you be able to do the Nav bar changes before then?  If not, then let's do this iteration and we will follow up with the other after the new year.

Definitely! I'm hoping to finish this up today 😃

**Comment by rogermparent** [comment]
This looks good with the latest changes! I think we're all set to merge after any finishing touches you find necessary- @julieg18 feel free to add your own approving review to let this merge go through, since I can't add one where this PR was created by me.

**Review by julieg18 — APPROVED** [review]

**Pull request merged**
