### PR TITLE
ref: reorg and wrap `import-url` usage block

### PR DESCRIPTION
**Pull request by jorgeorpinel**
Prevents horizontal scrolling in https://dvc.org/doc/command-reference/import-url#synopsis.

### CODE REVIEW

**Review by shcheklein — APPROVED** [review]
Same question though - we are changing the order here - is it updated in DVC?

**Comment by jorgeorpinel** [comment]
I tried updating it but for some reason can't open a PR from my fork on the core repo cc @dberenbaum can someone open it from this branch https://github.com/jorgeorpinel/dvc/tree/jorgeorpinel-patch-1 or give me access to?

image

Changes should look like this: https://github.com/iterative/dvc/compare/main...jorgeorpinel:dvc:jorgeorpinel-patch-1?expand=1

**Comment by efiop** [comment]
@jorgeorpinel https://github.com/iterative/dvc/compare/main...jorgeorpinel:dvc:jorgeorpinel-patch-1?expand=1 this doesn't work for you? That's very strange. Maybe there was some github glitch, could you try again?

**Comment by jorgeorpinel** [comment]
Working now. Yes either a glitch or something I missed... See https://github.com/iterative/dvc/pull/8785, thanks.

**Pull request merged**
