### PR TITLE
More misc. updates

### PR DESCRIPTION
**Pull request by jorgeorpinel**
A bit less random than #2296 but still a continuation of the same process (cleaning up my git stash post 2.0 release)

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
For some reason this PR still shows all the changes that were already merged in #2296. So far only 4ae8b92 should be different.

**Comment by jorgeorpinel** [comment]
OK I'm not sure what's going on here but can we merge this just with 4ae8b929ba0f69a6e740981cb59df8d5af1913b1 @shcheklein ? All the other changes were also included in https://github.com/iterative/dvc.org/pull/2296/files yet they're shown here (https://github.com/iterative/dvc.org/pull/2297/files) too...

Only the changes to https://github.com/iterative/dvc.org/pull/2297/files#diff-cb7661d07797ae9df6a1047fee86faa5bac42f4283028dcebf5c118b53050c90 are new here. Maybe merging this will fix up the GH history.

**Comment by shcheklein** [comment]
Hmm, can we create a new PR with the relevant changes?

**Comment by jorgeorpinel** [comment]
OK. I checked the website and all the other commits seem to be reflected in the content so 🤷 

Closing this.

**Pull request closed without merging**
