### PR TITLE
Update live-metrics-and-plots.md

### PR DESCRIPTION
**Pull request by daavoo**
Better to showcase `save_dvc_exp=True` by default.

### CODE REVIEW

**Review by mvshmakov — APPROVED** [review]
Thanks!

**Comment by tapadipti** [comment]
Can we add a line describing what `save_dvc_exp=True` does? For users who may not be familiar with it.

**Review by shcheklein — APPROVED** [review]

**Comment by tapadipti** [comment]
@daavoo Why is it better to showcase `save_dvc_exp=True` by default; what benefit does it provide to the user? Can we pls mention this in the docs, for unfamiliar users?

**Comment by daavoo** [comment]
> @daavoo Why is it better to showcase `save_dvc_exp=True` by default; what benefit does it provide to the user? 

In the current description in https://dvc.org/doc/studio/user-guide/projects-and-experiments/live-metrics-and-plots#send-and-view-live-metrics-and-plots , DVC or DVC Pipelines are not mentioned as a requirement (or mentioned at all).

Showing `save_dvc_exp=True` will ensure that an experiment gets created with or without a DVC Pipeline. 

> Can we pls mention this in the docs, for unfamiliar users?

As of today, the only reference for what I described above is https://dvc.org/doc/dvclive/how-it-works#track-the-results . We could add a link to that.

I am working on updating the https://dvc.org/doc/start/experiment-management/experiments guide and hope that we can link to there in the future.

**Pull request merged**
