### PR TITLE
Rename all references to `get-started-experiments` to `example-dvc-experiments`

### LINKED ISSUE #2784: Rename all references to `get-started-experiments` to `example-dvc-experiments`
There are some published references in to `get-started-experiments` in the docs,
most notably in UG:Sharing Experiments page. Need to replace them with the
references to `example-dvc-experiments`.

### PR DESCRIPTION
**Pull request by iesahin**
Fix #2784

### CODE REVIEW

**Review by shcheklein — APPROVED** [review]

**Review by jorgeorpinel — APPROVED** [review]
Worth letting the Studio team know of the repo change BTW

Per https://studio.iterative.ai/team/Iterative/views/example-get-started-zde16i6c4g (referenced in https://dvc.org/doc/start)

**Comment by jorgeorpinel** [comment]
Oops just tagged 10 people sorry

**Comment by mvshmakov** [comment]
Hey, @jorgeorpinel, thanks for letting us know!

You can access by this the link another repo which is called `example-get-started`, not `get-started-experiments`. I haven't found any references in our codebase to this repo. In addition, in the parent issue, there is nothing about the `example-get-started` repo, so we should be fine here.

Or do you mean we should use this experiments repo as the demo one / replace a link in the dvc.org to this one: https://studio.iterative.ai/team/Iterative/views/example-dvc-experiments-vcvfbtzapg?

**Comment by jorgeorpinel** [comment]
I'm not up to date on what's the final plan about the official example repo but @iesahin can confirm. Based on that you can decide whether to keep or change the studio default example project @mvshmakov. Thanks

**Pull request merged**
