### PR TITLE
blog: July Heartbeat

### PR DESCRIPTION
**Pull request by jendefig**
This pull request migrates from [#3673](https://github.com/iterative/dvc.org/pull/3673) which will close.

July Heartbeat
Publish Date: July 18th.

- [x] There are no grammatical errors, jargon, or obvious stylistic issues. (for reviewer to check)
- [x] Have images been run through tiny.png?
- [x]  Are all lines 80 characters or less?
- [x] Are Oxford commas observed?
- [x] Content Creator has done a complete review for typos/language after taking a break from content
links checked in the piece
- [x] Have reviewed what the piece looks like on your own [[machine using yarn develop](https://dvc.org/doc/user-guide/contributing/docs#development-environment)](https://dvc.org/doc/user-guide/contributing/docs#development-environment)
- [x] changed discuss link

### CODE REVIEW

**Comment by jendefig** [comment]
@flippedcoder, @RCdeWit has reviewed in the previous version and I made the revisions.  I've corrected the Discuss link, the awesome image is appropriately sized.  Let me know if you see anything else! Thanks for your help this morning!

**Comment by jendefig** [comment]
@rogermparent All the links that it's having a problem with are ok; they're not 404s.  Do I need to do anything here?

**Comment by rogermparent** [comment]
> @rogermparent All the links that it's having a problem with are ok; they're not 404s. Do I need to do anything here?

Nope, that's something we can try to account for on the `link-check` end. It's like an arms race against websites that don't want to be scraped :grimacing:, sorry for the inconvenience!

**Comment by jendefig** [comment]
@rogermparent Could you please approve this so that it can be merged?

**Pull request merged**
