### PR TITLE
exp: Drop `init`.

### PR DESCRIPTION
**Pull request by daavoo**
Closes https://github.com/iterative/dvc.org/issues/4336

### CODE REVIEW

**Comment by shcheklein** [comment]
@daavoo can we please do on thing at a time? :)

Are we in agreement that we don't support checkpoint anymore? (I'm personally still not convinced. Primarily because I'm not sure we have a decent replacement for this. I think it's needed if we were to remove this).

**Comment by daavoo** [comment]
> @daavoo can we please do on thing at a time? :)

Updated to only remove `exp init`.

> Are we in agreement that we don't support checkpoint anymore? (I'm personally still not convinced. Primarily because I'm not sure we have a decent replacement for this. I think it's needed if we were to remove this).

I will create an issue and comment in https://github.com/iterative/vscode-dvc-demo (afaik the only active demo using checkpoints)

**Comment by daavoo** [comment]
> > Are we in agreement that we don't support checkpoint anymore? (I'm personally still not convinced. Primarily because I'm not sure we have a decent replacement for this. I think it's needed if we were to remove this).
> 
> I will create an issue and comment in https://github.com/iterative/vscode-dvc-demo (afaik the only active demo using checkpoints)

https://github.com/iterative/vscode-dvc-demo/issues/65

**Comment by dberenbaum** [comment]
@daavoo Since you dropped checkpoints from this, I think there's a reference we need to drop in https://dvc.org/doc/user-guide/experiment-management/checkpoints. 

Also, should we stop showing `dvc exp init` in the CLI as well?

**Review by omesser — APPROVED** [review]

**Comment by dberenbaum** [comment]
> @daavoo Since you dropped checkpoints from this, I think there's a reference we need to drop in https://dvc.org/doc/user-guide/experiment-management/checkpoints.

Pushed an update to address this.

**Review by dberenbaum — APPROVED** [review]

**Pull request merged**
