### PR TITLE
blog: GSoD 2020 post improvements

### PR DESCRIPTION
**Pull request by jorgeorpinel**
Preview @ https://dvc-landing-gsod-mkn8cutqbcgst.herokuapp.com/blog/gsod-ideas-2020

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Hi @casperdcl do you know why the link checked script wants https://dvc.org/uploads/images/2020-04-30/tooltip.png to exist in order to pass? 🙂 The link is `/uploads/images/2020-04-30/tooltip.png` in the code. Please see https://circleci.com/gh/iterative/dvc.org/3296

**Comment by shcheklein** [comment]
@jorgeorpinel disregard the check if image actually exists

**Comment by casperdcl** [comment]
Not sure about the question @jorgeorpinel - do you mean the `/uploads/images/...` code actually refers to a base url other than https://dvc.org?

**Comment by casperdcl** [comment]
Ah I see the new file is part lf this PR, so yes it'll fail until it's actually merged.

@shcheklein What do you think about running a local webserver in the CI and checking against base URL http://localhost?

**Comment by jorgeorpinel** [comment]
Seems like the easiest way is to ignore this. Running a local server sounds like overkill (build, serve, etc). Any way it can know when there's a preview deployment? In this case it's https://dvc-landing-gsod-mkn8cutqbcgst.herokuapp.com/ but not every PR will have one.

**Comment by shcheklein** [comment]
@casperdcl running it will complicate the check significantly - it takes minutes to build the app. 

could we somehow run/re-run this check after preview is done and get the preview URL from the Github itself?

**Comment by shcheklein** [comment]
> Seems like the easiest way is to ignore this.

simple, but breaks the flow - merging only ✅ ... which easily leads to merging it with some major issues.

**Comment by jorgeorpinel** [comment]
Merged per agreement to iterate quickly on these improvements. I think it only needs one more PR, not as big as this one. Will send ASAP

**Pull request merged**
