### PR TITLE
document `--run` for `dvc stage add`

### PR DESCRIPTION
**Pull request by skshetry**
See https://github.com/iterative/dvc/pull/9487

### CODE REVIEW

**Comment by skshetry** [comment]
> Should we also add a deprecation notice for `dvc run`?

We should at least wait for 2-3 minor releases before deprecating, it was just released.

**Comment by dberenbaum** [comment]
@skshetry I mean we should add a notice now that it's being deprecated. It won't be actually deprecated until 3.0. That should help make it less surprising when we drop it.

Related: https://github.com/iterative/dvc.org/pull/4443#issuecomment-1557191650

**Comment by skshetry** [comment]
Right, but there’s no alternative for users yet.

**Comment by dberenbaum** [comment]
Sorry, I still don't get it. What is the harm in putting a notice in the docs now that it will be deprecated in 3.0? If users don't upgrade, they can continue to use it. If they go to the docs, it would help for them to know ASAP that they can't keep relying on it for much longer.

**Pull request merged**
