### PR TITLE
Update link-check to 0.8 for ref link support

### PR DESCRIPTION
**Pull request by rogermparent**
After https://github.com/iterative/link-check/pull/6

### CODE REVIEW

**Review by jorgeorpinel — DISMISSED** [review]
Let's do this 🚀 

Will try on #2534

**Comment by jorgeorpinel** [comment]
> Hmmm wait. The check is failing. Can't find v0.8 yet?

Cc @rogermparent see https://github.com/iterative/dvc.org/pull/2599/checks?check_run_id=2965875118

**Comment by rogermparent** [comment]
Oops! I pushed the commit but not the tag. Will fix ASAP and report back.

**Comment by rogermparent** [comment]
Alright, tag's pushed and CI went through!

**Review by jorgeorpinel — APPROVED** [review]

**Pull request merged**
