### PR TITLE
using GCP remote blog: minor cleanup

### PR DESCRIPTION
**Pull request by shcheklein**

### CODE REVIEW

**Comment by shcheklein** [comment]
@flippedcoder I made all the code blocks look the same and highlighted, ptal

also, images - tbh it seems you took a very large portion of the screen. They look consistent, but very hard to read. We can subtitle (click to open), we can also highlight/zoom the proper place on the screen to pay attention to. I would make way easier to read.

and one more question (sorry that it's so late after we merged this, no need to fix this probably - may be add a note?) - why do show the service account workflow? By default I though that just your personal account is enough, if GCP tools are setup locally you don't need extra credentials, etc? Service accounts are needed usually to automate things or for extra layer of security.

**Comment by shcheklein** [comment]
cc @flippedcoder

**Comment by flippedcoder** [comment]
> why do show the service account workflow?

I think when the idea originally came up, there were some DVC users getting confused in that part of the flow so this is just here to help them out.

**Review by flippedcoder — APPROVED** [review]

**Comment by shcheklein** [comment]
@flippedcoder yes, but there should be then a better motivation / explanation when service accounts make sense. They have a cost of using them.

**Comment by shcheklein** [comment]
@flippedcoder and this blog post looks like a general / recommended way of doing auth. People will be coming and reading this w/o even realizing there are other (usually simpler ways) to do this + w/o any help navigating through the different options.

**Pull request merged**
