### PR TITLE
try embedding video in docs

### PR DESCRIPTION
**Pull request by elleobrien**
This is in response to Issue #1807- how to put video docs in the Getting Started pages. Any suggestions for formatting or ideas for introducing the video are welcome.

### CODE REVIEW

**Comment by shcheklein** [comment]
Looks like a duplicate

**Comment by elleobrien** [comment]
@shcheklein not a duplicate- one PR was to change video on the front page, this is to embed a video in the Getting Started docs

**Comment by shcheklein** [comment]
@elleobrien I think that PR has already embedded video in the Getting Started :) It's already deployed.

**Comment by elleobrien** [comment]
ahhh yes! you're right, this happened because I made the branch for the
landing video from my local workspace after submitting the PR for the
Getting Started docs. Lost track there :)

**Pull request closed without merging**
