### PR TITLE
Upgrade to Gatsby 4 and fix images paths that broke builds

### PR DESCRIPTION
**Pull request by rogermparent**
I decided to use Gatsby 3 in #2447 since Gatsby 4 was still in beta, most plugins hadn't updated to match it, and it seemed to be a bit less stable in Heroku builds.

Since then, Gatsby 4 has left beta and most plugins have updated to work with it. Also, Gatsby Cloud's image processing has integrations specific to 4, so this PR will be used to test on Gatsby Cloud.

Also, it seems one of the upgrades since then has made it to that builds fail when an image path isn't found- this is a good thing, since we had a few images that were completely broken and just unnoticed, and some "phantom" images that worked when they shouldn't have.

This PR also updates the `typescript` and `eslint` packages, which was required because `react-use` uses named tuples, a feature introduced in newer TypeScript versions, and eslint needed to be upgraded alongside TypeScript. 
I also upgraded `stylelint`, which then discovered a whole ton of CSS problems that we had before, including obvious stuff like duplicated keys. The results of `stylelint --fix` ended up being the bulk of the PR's diff.

### CODE REVIEW

**Review by julieg18 — COMMENTED** [review]
Looks great! 

I noticed that the cards in the Doc's home page is styled differently:

image

I have no idea why though 🤔

**Comment by rogermparent** [comment]
@julieg18 Great catch on the card collapsing! I'm not sure why that would have changed, I know the major upgrade on `github-markdown-css` caused some issues, but I don't see how it would cause this completely custom flex setup to start breaking down.

I just fixed it by using slightly more proper `margin`-based spacing, though I had to apply it vertically to `cardWrapper`s and horizontally to `card`s, it wouldn't work otherwise.

**Comment by rogermparent** [comment]
Not sure why Restyled is trying to change this, running `format-all` locally doesn't apply any changes, and the changes restyled is asking for cause `lint-ts` to break.

**Comment by julieg18** [comment]
> Not sure why Restyled is trying to change this, running `format-all` locally doesn't apply any changes, and the changes restyled is asking for cause `lint-ts` to break.

I think I had the same issue when I tried to edit that particular file that Restyled is trying to restyle. I think it had something to do with the kind of environment that Restyled is using to run code.

**Comment by rogermparent** [comment]
I took a check around all the top-level pages and usages of the `cards` custom component, I haven't caught anything obvious. Willing to give this time for another once-over to be extra sure, but I think we're ready to send this in (and probably deal with some link check errors :sob:)

**Review by julieg18 — APPROVED** [review]
Looks good!

**Pull request merged**
