### PR TITLE
Adding Getting Started on CML with GitLab instructions

### PR DESCRIPTION
**Pull request by jendefig**
Ok.  Hoping this works this time.  I didn't add the images and a package.json file last time....

### CODE REVIEW

**Comment by shcheklein** [comment]
@jendefig two things:

- there should not be the `package-json.lock` file. Could you please remember what did you run to generate it? It is usually generated if you run `npm` instead of `yarn`.
- please, use your personal email for commits, or set the one you use in GH settings so that GH properly attributes those to you (https://github.community/t/why-is-my-commit-associated-with-the-wrong-person/10199):

Screen Shot 2021-02-09 at 12 12 05 PM

**Comment by shcheklein** [comment]
@jendefig also, please create a branch right in the repo, no need to do a fork. It'll be automatically deployed for you then and you can see the app running for the PR and we can review it online.

**Comment by jendefig** [comment]
Ok.  I commented about this in the one I did yesterday with the code I was getting and that I don't know why that .json file is there.  When I was trying to set up yarn it was giving me errors even in the new mac computer.  So in order to get it to work, my husband did an npm install to resolve the dependencies before I could do yarn develop.  Then it worked. If I just went to yarn develop there were errors.  So what do I do now?  Uninstall everything and start over?

I made a corrections to the style guide instructions yesterday too, so that needs to be rejected if this was wrong.  But I  was having trouble getting it to work otherwise.

**Comment by shcheklein** [comment]
@jendefig let me try to reproduce this locally, it might be something related to the latest version of Node/yarn. Could you please run `yarn --version` + `node --version`?

**Comment by jendefig** [comment]
image

**Comment by shcheklein** [comment]
@jendefig thanks!


could you also please clone it and run `yarn` + `yarn develop` and copy output please?

**Comment by jendefig** [comment]
Do clone it straight from iterative?

**Comment by jendefig** [comment]
And if I do that it will run over the files I made, right?  So I first need to change my version on my computer to another name, correct?  Remember you are dealing with a supreme newbie!

**Comment by shcheklein** [comment]
@jendefig just a fresh clone from the `iterative/dvc.org`:

```
git clone git@github.com:iterative/dvc.org.git
yarn
yarn develop
```

**Comment by jendefig** [comment]
After first step...

image

**Comment by jendefig** [comment]
Nope, Not that....

**Comment by jendefig** [comment]
image

**Comment by jendefig** [comment]
So ran with Https instead...
image

**Comment by jendefig** [comment]
Ok.  Soooo that error was because I forgot that I have to cd to dvc.org... So now I think it's working, but there is that note about caniuselite and run....  Should I do that?

image

**Comment by shcheklein** [comment]
That's it! it should be working 🎉 

you should be able to open a local copy in your browser now. Put `http://localhost:8080/` in it.

Now you can change some `.md` files and will see the page changes in the browser.

Next step, will be trying to do a commit with your changes and see that:

```
git commit "something"
> fails and fixes your file
git commit "something"
```

that this flow works ^^

**Comment by jendefig** [comment]
Ok.  I added and committed then pushed.  I got an error.  So I went and unchecked the keep email private box (It was already on my personal email.).  And still got the same when I tried again...
image

**Comment by shcheklein** [comment]
@jendefig okay, we are almost there! First you need to fix the configuration as Git suggest you to do:

`git config --global --edit` 

You need to specify your name (it looks correct) and your email (it looks wrong). Email should be the same as the one you use for GitHub.

After that you can undo the previous commit `git reset --soft HEAD^` and you need to create a brach. It complains since you are trying to push directly into the `master` branch of this repo, which is protected - it has to be PR first:

`git checkout -b "improve-cml-docs"`

after that you do your commit and do `git push origin HEAD` to push the brach.

In the GitHub interface you will be able to create a PR out of this branch.

Please give it a try, and let me know if something doesn't work.

**Comment by jendefig** [comment]
This pull request is outdated.  The new corrected pull request for this document can be found at #2176

**Pull request closed without merging**
