### PR TITLE
Prevent deployment check on master via deployment ref

### PR DESCRIPTION
**Pull request by rogermparent**
Suppressing the link check on master is eluding me, so I made this branch to help diagnose and solve the issue for good.

### CODE REVIEW

**Comment by rogermparent** [comment]
Oh. The `ref` on the `deployment_status` payload is a blank string. Fantastic.

**Comment by rogermparent** [comment]
Alright, so even though `ref` isn't in the base github context for `deployment_status`, there is a `ref` in the `deployment` event that's formatted as the branch name alone.

I did this with data dumps in the test repo, but also found official docs [here](https://developer.github.com/webhooks/event-payloads/#webhook-payload-example-8)

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
@rogermparent is it ready to be merged?

**Comment by rogermparent** [comment]
@shcheklein Yep, it's ready!

**Pull request merged**
