### PR TITLE
Regular updates (Apr 7)

### PR DESCRIPTION
**Pull request by jorgeorpinel**
- link-check script fixes
- 
- misc. stuff

### CODE REVIEW

**Comment by shcheklein** [comment]
34 changed files - expected?

**Comment by jorgeorpinel** [comment]
No. Something isn't right. Idk why it's showinf a bunch of commits from 20 days ago...

**Comment by jorgeorpinel** [comment]
I probably messed up here... I'll reopen a correct one.

**Comment by jorgeorpinel** [comment]
Sone: #1126

**Pull request closed without merging**
