### PR TITLE
Remove run experiment sections of Studio docs

### PR DESCRIPTION
**Pull request by jellebouwman**
Docs cleanup that supports https://github.com/iterative/studio/issues/8077

In https://github.com/iterative/studio/issues/8077 we discussed that we want to remove the run experiment sections from Studio for now. We've started work and when https://github.com/iterative/studio/pull/8246 lands, Studio FE will no longer have a way for users to create new experiments directly from DVC Studio.

This PR cleans up the main sections that talk about this feature.

We'll have to add back the CI workflow generation section (Studio counterpart tracking here: https://github.com/iterative/studio/issues/8296)

### CODE REVIEW

**Review by shcheklein — APPROVED** [review]

**Comment by tapadipti** [comment]
@jellebouwman I've created a [new PR](https://github.com/iterative/dvc.org/pull/4997) with more changes. ptal.

**Comment by dberenbaum** [comment]
I think we also need to revise https://dvc.org/doc/user-guide/experiment-management/running-experiments#running-the-pipelines-on-cloud.

**Comment by jellebouwman** [comment]
@dberenbaum removed that per your suggestion in 

Also checked the links we use in Studio, and it seems that all of the links to the Studio docs make sense. I've removed one FAQ answer that didn't make much sense (https://github.com/iterative/studio/pull/8312), but I believe all the links are working properly 👍

**Comment by dberenbaum** [comment]
@jellebouwman One last request - can you rename https://dvc.org/doc/user-guide/experiment-management/running-experiments#running-the-pipelines-locally from `Running the pipeline(s) locally` -> `Running the pipeline(s)`?

**Comment by jellebouwman** [comment]
Got it @dberenbaum - addressed in https://github.com/iterative/dvc.org/pull/4996/commits/d2d6ec2a1b1cf3f59d34681ba9c94ba34d04223b

**Pull request merged**
