### PR TITLE
fix: link to Experiments (index page)

### PR DESCRIPTION
**Pull request by jorgeorpinel**
per https://github.com/iterative/dvc.org/pull/4271#pullrequestreview-1272139385

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Not sure how these passed PR link checks. Do we need a post-mortem?

**Review by yathomasi — APPROVED** [review]
> Not sure how these passed PR link checks. Do we need a post-mortem?

Did we not have the redirects? Yeah, it looks like we need to take a look. cc: @rogermparent

**Review by rogermparent — APPROVED** [review]
Apologies for this happening :pray: 

I don't think it's as complex as requiring a post-mortem, but it's a weakness in our link check setup which hasn't been addressed: only checking diffs, while efficient, doesn't account for the case where changing something a link points to isn't picked up since the link itself was never in a diff. I can still write one up if we think it'd be good to have.

Link check has definitely languished as other things take priority, but it's definitely no excuse that this was able to sit for so long. We do have a whole-repo link checker, but it's hard to monitor since it doesn't have output. I think CML-ifying it could be an easy upgrade that lets everyone easily see broken links. I'll do that today.

**Comment by jorgeorpinel** [comment]
Thanks! I didn't mean something that formal really. I was just curious as to how it might have happened, and now I know.

> Did we not have the redirects?

I think that there was a temporary (302) redirect from /doc/user-guide/experiment-management to /doc/user-guide/experiment-management/experiments-overview before and that was simply removed then the latter ceased to exist. We just somehow forgot to update all the links, oops -- that was probably me :p

**Comment by jorgeorpinel** [comment]
U: I wasn't able to find the redirects change I was referring to ([this](https://github.com/iterative/dvc.org/pull/3956/files#diff-a6828b19e9794c1fbb6799ea95263fb7487b676d054932b5f6e3b315eb12a6a2) is the closest). I suppose it can't hurt to add a redirect since these links were broken: See https://github.com/iterative/dvc.org/pull/4275.

**Pull request merged**
