### PR TITLE
Added january events

### PR DESCRIPTION
**Pull request by flippedcoder**
Adding the upcoming events we have for January.

### CODE REVIEW

**Review by shcheklein — CHANGES_REQUESTED** [review]
Thanks for the update @flippedcoder ! Can we make the python web conf image smaller / run it through tinypng? It's 0.5MB which looks too much.

**Review by jendefig — APPROVED** [review]

**Comment by shcheklein** [comment]
I assume this is outdated @jendefig @flippedcoder ? Do we need this? If not - let's close, if yes - please let's discuss how is responsible for moving things forward when there is no response for a review for a while. wdyt?

**Comment by flippedcoder** [comment]
@shcheklein I lost track of this PR so sorry about that. We'd still like this merged in since there are some upcoming events and I've updated the image.

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
Thanks @flippedcoder , merged.

**Pull request merged**
