### PR TITLE
Added full stop

### PR DESCRIPTION
**Pull request by chaytanyasinha**
Added full stop in the end of a sentence in privacy.md

### CODE REVIEW

**Comment by shcheklein** [comment]
@chaytanyasinha please rebase to fix the CI check

**Comment by chaytanyasinha** [comment]
@shcheklein I think I ran prettier.Can you please tell the command and when to use so that I can cross check.

**Comment by jorgeorpinel** [comment]
I think you can just fetch upstream, pull master, and merge it into your branch. Or just apply the change again from the latest master and open the PR again.

I'm not really sure why the CI check is failing on a file that's not part of this PR @shcheklein was something committed to master directly without formatting by accident? Strange

**Comment by chaytanyasinha** [comment]
@shcheklein @jorgeorpinel can you please tell the prettier command to be used in git bash. I think it's doing some problem from there.

**Comment by jorgeorpinel** [comment]
@chaytanyasinha all the commands used by CI and others are explained here: https://dvc.org/doc/user-guide/contributing/docs#all-commands

Your dev environment runs the formatting automatically. The problem here is with a file that you didn't change, not something you caused. It sounds like this has since been fixed in the master branch which is why Ivan suggested you rebase yours. Merging, cherry-picking, or just doing your small change again from the latest master and submitting the PR again should also work.

https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by chaytanyasinha** [comment]
@jorgeorpinel okay I got it.

**Comment by jorgeorpinel** [comment]
Hey @chaytanyasinha I just applied this myself to my latest branch and tagged you in 67f06480. Thanks

**Pull request closed without merging**
