### PR TITLE
glossary: make tooltip IDs unique

### LINKED ISSUE #644: glossary: wrong tooltip direction on repeated keywords
The direction for tooltip for `DVC cache` is returned correctly but not for `cache` below. This is happening since the keys are not unique.
bug

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #644

### CODE REVIEW

**Comment by shcheklein** [comment]
@algomaster99 please, merge master, to run eslint new workflow in CircleCI

**Comment by algomaster99** [comment]
@shcheklein I have merged the master. How to run the following things?

**Comment by shcheklein** [comment]
@algomaster99 it's not merged yet, I think

**Comment by jorgeorpinel** [comment]
@algomaster99 to merge master, in your local `fix-tooltip-direction` branch run:

```console
$ git fetch --all
... # should see that origin/master is updated
$ git merge origin/master
... # solve conflicts if necessary.
    # otherwise just confirm and save merge commit message.
$ git push
...
```

**Comment by algomaster99** [comment]
Done!

**Comment by shcheklein** [comment]
@algomaster99 yep, take a look at results here - https://circleci.com/gh/iterative/dvc.org/922?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by jorgeorpinel** [comment]
> take a look at results here - https://circleci.com/gh/iterative/dvc.org/922

Niceeee @shcheklein. We should update the contributing docs page to explain the new CI tests probably? And how to run them locally?

**Comment by jorgeorpinel** [comment]
p.s. I see https://dvc.org/doc/user-guide/contributing-documentation already reads "If you intend to change JavaScript files, test the changes with `yarn test` command before committing them." but what about `yarn lint`?

**Comment by shcheklein** [comment]
@jorgeorpinel good point, we can mention `yarn lint`. CircleCI will run it for you anyway though :)

**Comment by jorgeorpinel** [comment]
OK @shcheklein, I added a note in https://github.com/iterative/dvc.org/pull/671/commits/e74cbc1c966751637726093a856d4bc308b6ee71 (see it [in review app](https://dvc-org-pr-671.herokuapp.com/doc/user-guide/contributing-docs#submitting-changes)).

But I realized we have 2 scripts for similar purposes: `yarn pretty` (uses `pretty-quick`) and `yarn lint` (uses `eslint`). Both are enforced locally with a Git pre-commit hook but this could be disabled by the developer. The CI only enforces the latter, `yarn lint`. Is this correct? Seems strange to me.

**Comment by jorgeorpinel** [comment]
Actually, let me move this discussion to PR #671...

**Pull request merged**
