### PR TITLE
Mostly link-related (regular) updates

### PR DESCRIPTION
**Pull request by jorgeorpinel**

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Hey @casparjespersen `yarn link-check` is failing in this PR (see https://circleci.com/gh/iterative/dvc.org/2147) but it's finding links that I removed from the code base. Maybe it's not checking the PF branch but rather the base branch? `master` in this case. Maybe the logic below isn't correct?

https://github.com/iterative/dvc.org/blob/2982546117fc2451110e8f82678392c9e6077165/.circleci/config.yml#L23-L30

**Comment by jorgeorpinel** [comment]
p.s. `yarn link-check` has no errors when I run it locally on this branch.

**Comment by casperdcl** [comment]
@jorgeorpinel you mean @casperdcl not `@casparjespersen` :)

**Comment by jorgeorpinel** [comment]
Yeah this GH handle autocompete is terrible. Keeps wanting me to ping people who might have commented once in a single issue of the project...

**Comment by jorgeorpinel** [comment]
Cool, link check is working after #979. Thanks @casperdcl !

**Comment by jorgeorpinel** [comment]
As noted in https://github.com/iterative/dvc.org/issues/974#issuecomment-583273943, the link check is currently crashing, preventing the CI checks here from completing ATM. Otherwise this is ready for review.

**Comment by casperdcl** [comment]
ok finally got around to reviewing this. Will try to re-fix in a new PR. Not sure why you re-ordered links in `exclude-links.txt` - probably best to keep sorted.

**Comment by jorgeorpinel** [comment]
I think I just sorted them alphabetically by domain name. If you leave a PR review here I'll address in a separate one.

**Comment by casperdcl** [comment]
hmm you mean you strip `http(s)://` before sorting? Seems unnecessarily inconvenient. Will be fixed in #997 anyway...

**Comment by jorgeorpinel** [comment]
And www. But no, whatever is easy, as long as we all know what the sorting is. Thanks

**Comment by jorgeorpinel** [comment]
p.s. I don't assume the file supports comments (and blank lines)? I.e.
```
# This is a list of URLs to exclude from scripts/...
# It's ordered with GNU `sort`.

http://127.0.0.1/
...
```

**Comment by casperdcl** [comment]
I was nearly going to write comments. They should be fine to add (though strictly speaking aren't ignored yet)

**Pull request merged**
