### PR TITLE
Docs: Commands update: add/get/get-url/import-url - adding force flag

### PR DESCRIPTION
**Pull request by omesser**
> You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

added in DVC here: https://github.com/iterative/dvc/pull/9365

### CODE REVIEW

**Comment by omesser** [comment]
Let's only merge after next DVC release, with https://github.com/iterative/dvc/pull/9365

**Review by dberenbaum — APPROVED** [review]
LGTM, thanks @omesser!

Unrelated, but maybe we should drop the `desc`, `type`, and `labels`? I see you put them at the end, and now that we have `artifacts:` in `dvc.yaml`, these fields do seem confusing/redundant. If you agree, we can make a new issue and I can add it the 3.0 deprecation list.

**Comment by aguschin** [comment]
I'd say, let's add it to deprecation list to revisit them before 3.0 and check once again that we don't need them (taking into account the MR state we'll have on that date).

**Comment by dberenbaum** [comment]
> I'd say, let's add it to deprecation list to revisit them before 3.0 and check once again that we don't need them (taking into account the MR state we'll have on that date).

Added to https://github.com/iterative/dvc/issues/7093

**Comment by omesser** [comment]
[DVC 2.56.0](https://github.com/iterative/dvc/releases/tag/2.56.0) released, this can now be merged

**Pull request merged**
