### PR TITLE
allow-missing: warn about 3.0 changes

### PR DESCRIPTION
**Pull request by dberenbaum**
When using `repro/exp run --allow-missing` with data saved before 3.0, the `--allow-missing` flag will fail to skip the data because the hash type has changed from `md5-dos2unix` to `md5`.

I'm not sure what to suggest as the right workaround. Should they do `dvc remove` followed by `dvc add` again?

### CODE REVIEW

**Comment by pmrowla** [comment]
> I'm not sure what to suggest as the right workaround. Should they do `dvc remove` followed by `dvc add` again?

Doing `dvc cache migrate --dvc-files` should work here

**Comment by dberenbaum** [comment]
@yathomasi Any idea why the build is failing?

**Comment by yathomasi** [comment]
> Any idea why the build is failing?

It was because of an expired GH token. I had it updated for main `dvc.org` deployment but I thought we didn't use it for preview deployments. I have updated it now with a valid GH token. 

Personally, I don't think we would need it in preview apps, as it's only for live GH live stars. Let me know if it's okay if I drop it and which means we will miss live GH stars in preview deployment and show some static random value `8888`.

**Comment by dberenbaum** [comment]
> Personally, I don't think we would need it in preview apps, as it's only for live GH live stars. Let me know if it's okay if I drop it and which means we will miss live GH stars in preview deployment and show some static random value `8888`.

Yup, sounds good @yathomasi, thanks!

**Comment by dberenbaum** [comment]
ping @iterative/dvc. Could someone review this so we can get it merged please?

**Review by efiop — APPROVED** [review]

**Review by pmrowla — APPROVED** [review]

**Pull request merged**
