### PR TITLE
Improve CloudFlare cache cleaner logging + Stars bugfix (second attempt)

### PR DESCRIPTION
**Pull request by rogermparent**
This is the same PR as before, but with a slight change to fix the server invocation.

This time I'll confirm the review app before I suggest a merge.

### CODE REVIEW

**Comment by rogermparent** [comment]
Yep, adding `node` back to the invocation makes the proxy server actually work!

https://dvc-landing-fix-cloudfl-jkfbz8.herokuapp.com/

**Comment by shcheklein** [comment]
Deploying? :)

**Comment by rogermparent** [comment]
Yep, it's deploying successfully now! With the slight change to the server, deploy previews are successful. I must have been using only `gatsby serve` before and missed where I broke the server invocation because it can't be directly run like `clear-cloudflare-cache` was before.

**Comment by rogermparent** [comment]
Yay! The site's not broken!

**Pull request merged**
