### PR TITLE
Added links to contribute pages in the Community header

### PR DESCRIPTION
**Pull request by sarthakforwet**
References #1827.

### CODE REVIEW

**Comment by shcheklein** [comment]
@sarthakforwet thanks!! it's great, but looks too excessive to my mind. We should integrate this properly into the page.

**Some ideas:**

- Make `code` and `docs` links in the very first sentence
- Instead of Go to Github - link to the Contribution section

Any other ideas are welcome, but it should be properly integrated onto Desktop/Mobile, etc.

**Comment by sarthakforwet** [comment]
> Make code and docs links in the very first sentence

Nice idea @shcheklein! But I am kind of unaware as how we can club both the text and the link in the same sentence. (HTML tags do not work with json values). One midway could be to remove the sentence and add links to the guides for Doc contribution and Code Contribution.

  > Instead of Go to Github - link to the Contribution section

I think we must have this "Go to GitHub" button as a user would be more likely to click on it rather than going to GitHub on their own.

---------------------------------------------------------------------------------------------------------------------------------------------
The second idea that came to my mind is, what about adding cards for describing the Doc and Code contributions also.
Cards for doc and code contributions could be made similar to these-

image

**Comment by shcheklein** [comment]
@sarthakforwet 

> But I am kind of unaware as how we can club both the text and the link in the same sentence. (HTML tags do not work with json values). One midway could be to remove the sentence and add links to the guides for Doc contribution and Code Contribution.

I'm not sure I understand this to be honest, could you elaborate please?

> I think we must have this "Go to GitHub" button as a user would be more likely to click on it rather than going to GitHub on their own.

sounds good.

> The second idea that came to my mind is, what about adding cards for describing the Doc and Code contributions also.
Cards for doc and code contributions could be made similar to these-

we'll have too many cards then?

**Comment by sarthakforwet** [comment]
> I'm not sure I understand this to be honest, could you elaborate please?

Consider this-
image

Now I am unable to figure out how would I change those string "code" and "docs" to anchor text as this sentence is stored as a json value in the code.

> we'll have too many cards then?

Agreed! But we can add them in a manner that they would cause minimum distortion. The more we encourage contribution the more they'll come.  I think adding cards would impact more! Your call next @shcheklein, what should we do?

**Comment by shcheklein** [comment]
> Your call next @shcheklein, what should we do?

So far the only idea that I like is to add links to the text- which we should find someone to implement. Otherwise we should ask for a designer input or come with more ideas on our own.

**Comment by jorgeorpinel** [comment]
Thanks for the work so far. Closing as stale for now. Feel free to reopen if there are significant updates to this. Thanks!

**Pull request closed without merging**
