### PR TITLE
test: links: fix failures

### LINKED ISSUE #974: fix broken links
- [ ] fix dead links detected by #958
  + see `daily` workflow builds on https://circleci.com/gh/iterative/dvc.org (e.g. https://circleci.com/gh/iterative/dvc.org/2131) for an up-to-date list
- [ ] should warnings (status codes `0xx`, `3xx` etc) be counted as errors instead?

### PR DESCRIPTION
**Pull request by casperdcl**
- fix dead links detected by #958
  + see `daily` workflow builds on https://circleci.com/gh/iterative/dvc.org (e.g. https://circleci.com/gh/iterative/dvc.org/2264) for an up-to-date list
  + [x] fix/replace https://en.wikipedia.org/w/skins/Vector/images/external-link-ltr-icon.svg
    * do we really need this link? It's in a code comment
    * from 59e399dcc1f4f0f by @iAdramelk
  + [x] fix links in `exclude-links.txt`
  + [x] sort `exclude-links.txt`
- [ ] should warnings (status codes `0xx`, `3xx` etc) be counted as errors instead?
- fixes #974
- continues #978

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
What's the logic behind the sorting?

**Comment by casperdcl** [comment]
er just piped though `sort`. Makes it easy to see diffs in future changes.

**Comment by casperdcl** [comment]
yay re-ran daily and succeeded: https://app.circleci.com/jobs/github/iterative/dvc.org/2292

**Comment by shcheklein** [comment]
I'm thinking if we should create an exclusion list on file level? (don't analyze tests?). To avoid adding a lot of links to the existing file? what do you think @casperdcl @jorgeorpinel ?

**Comment by casperdcl** [comment]
Well we could do comments both in js and markdown similar to `# noqa` in py/`flake8`

**Comment by casperdcl** [comment]
You mean this sort of thing?

```md
[md]http://dead.link <!-- noqa -->
```

```js
'http://dead/link' // noqa
```

**Comment by shcheklein** [comment]
more like specify somewhere that I would like to exclude `tests/**` ... `.gitinore`-like interface I would say?

**Comment by jorgeorpinel** [comment]
> exclusion list on file level... specify somewhere that I would like to exclude tests/** ... .gitinore

Yes, only certain js and the md files really matter here, so I would even make it a white list with a pattern to match (similar to what `prettier` accepts, maybe hard to implement though). The existing list could be scripts/.link-ignore and the path list in scripts/.link-config or even sent as arguments to link-check.sh from package.json

> Ideally if it could actually render all web pages and only look at actual `<a href="` and `<img src="` URLs, that would be great, but probably overkill to do a separate `yarn build` just for this.

**Comment by jorgeorpinel** [comment]
p.s. Would also be nice if these files can ignore `# comments` (and blank lines) to make them self-documenting.

**Pull request merged**
