### PR TITLE
dvcignore: add docs related to global dvcignore

### PR DESCRIPTION
**Pull request by meshde**
Documentation for changes made by https://github.com/iterative/dvc/pull/8280

### CODE REVIEW

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
Thanks @meshde ! 🙏 

Tests (linters) are failing on prettier:

```bash
$ prettier --check '**/*.{js,jsx,md,tsx,ts,json}'
Checking formatting...
```

@jorgeorpinel @rogermparent @yathomasi do you know why there is no Restyled PR and what it is the recommended workflow in these cases? can we enabled it back somehow with an explicit approvals, etc?

@meshde would you mind to install `pre-commit` (running `yarn` locally should do the trick) and amend the commit please?

**Comment by meshde** [comment]
@shcheklein thank you for your review!

The pre-commit hook had actually run for me. The failing lint check was unrelated to this PR and was failing on the main branch as well at the time I had initially raised the PR.

The check seems to be passing on the main branch now, so updating this PR with the main branch seems to have made the checks pass here as well!

**Comment by jorgeorpinel** [comment]
> do you know why there is no Restyled PR and what it is the recommended workflow in these cases? 

Restyled no longer supports 3rd party PRs because it's a [security vulnerability](https://github.com/restyled-io/restyled.io/wiki/2022.08.03-Attack-on-Forked-PRs).

Glad that the checks here are OK now though.

**Comment by jorgeorpinel** [comment]
My initial impression is that the table is great (similar to the one in `dvc config`) but adding a new header and the new bullet list may be too much. We can probably summarize this a lot. Please ping us again once https://github.com/iterative/dvc/pull/8280 is approved and we'll help get it there. Thanks

**Pull request closed without merging**
