### PR TITLE
Only update User OS after hydration

### PR DESCRIPTION
**Pull request by rogermparent**
rough fix for #3633 

Main problem is that it has to update after first render which is a problem shared with live GitHub stars

We could either remove the description or make its update transition friendlier, anything with less drawbacks will take an order of magnitude more effort to implement.

### CODE REVIEW

**Comment by yathomasi** [comment]
@rogermparent Great work pinning it down 👏 

> Main problem is that it has to update after first render which is a problem shared with live GitHub stars

If I understand correctly, updating the OS after the first render is okay because we can only get the client OS once the script is loaded to the client browser(I believe it's also the reason for the hydration issue). Also, with our existing implementation, it should also be doing the same.

> make its update transition friendlier

That would be great but I think right now silencing the error takes priority.

**Comment by shcheklein** [comment]
@rogermparent it's still a draft?

**Comment by rogermparent** [comment]
Sorry, I thought I had changed it to ready but must have been looking at the wrong tab or something

**Comment by shcheklein** [comment]
Let's ship it, but in general it takes surprisingly long to update the screen (drop down and GitHub). 

What had changed to cause this problem btw?

**Comment by rogermparent** [comment]
We've always had this problem, it's just that React 18 made hydration mismatches throw an error instead of log a warning. The whole process of hydration means that a static HTML file is sent first, renders fast, and then React kick in to hydrate where it expects the results to match up with that initial HTML, which makes UI bits that are different for every user more difficult than other website implementations.

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
thanks Roger, It's almost immediate now on prod, do you expect it taking that much longer after the deploy?

**Comment by rogermparent** [comment]
> It's almost immediate now on prod, do you expect it taking that much longer after the deploy?

I doubt it'd be much longer than it currently is on prod, as the GH stars currently are populated on first render and they're pretty quick on prod with the download button not much further ahead.

**Pull request merged**
