### PR TITLE
exp: drop `gc`.

### PR DESCRIPTION
**Pull request by daavoo**
https://github.com/iterative/dvc/pull/9273

### CODE REVIEW

**Comment by omesser** [comment]
@daavoo & @dberenbaum - should this be dropped from docs asap or only after 3.0 release (https://github.com/iterative/dvc/issues/7093) ?

**Comment by dberenbaum** [comment]
Generally, I'm fine to drop from docs without a major release, but let's hold off on these or put some kind of deprecation notice in the docs. It feels like we might only add confusion by dropping a bunch of commands from the docs that still show up in the CLI -- it's not very explicit.

**Comment by omesser** [comment]
@daavoo @dberenbaum  - marking blocked for now, please followup with a [deprecation notice](https://github.com/iterative/dvc.org/pull/4441#issuecomment-1501843878)

**Review by dberenbaum — APPROVED** [review]

**Comment by dberenbaum** [comment]
@daavoo No strong opinion from me. I'm approving these and leave it up to you whether to merge it. Let's just make sure we don't forget about syncing it when we actually do the 3.0 release.

**Comment by omesser** [comment]
Any news here?

**Comment by dberenbaum** [comment]
No news except that we are on track to push for 3.0 and include this. I'm still fine to either merge or wait.

**Review by dberenbaum — CHANGES_REQUESTED** [review]
@daavoo I think there's still a reference in https://dvc.org/doc/command-reference/exp. Can we actually add a deprecation notice there?

**Review by dberenbaum — APPROVED** [review]

**Review by dberenbaum — APPROVED** [review]

**Pull request merged**
