### PR TITLE
[WIP] Absorbing Core Features

### PR DESCRIPTION
**Pull request by VANRao-Stack**
#425
I have worked out how we could absorb the core features section into the rest of the documentation especially into more introsuctory docs. 

I understand that I was specifically asked to work on deleting redundant data from the understanding DVC section. However, I think I now understand what you meant by absorbing. I have worked out the case for absorbing core features. I am only facing a little difficulty in the following bullet. 

> Large data file versioning works by creating special files in your Git repository that point to the cache, typically stored on a local hard drive.

I was told that https://dvc.org/doc/user-guide/large-dataset-optimization, couldn't be considered as an introductory doc. But if my idea is right I still think I can merge the above bullet into the beginning of the User Guide or Get Started. 

> You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
What issue does this PR address/fix/close? Please add this basic info to the description, thanks.

**Comment by jorgeorpinel** [comment]
> I have worked out the case for absorbing core features.

@VANRao-Stack is this PR meant to be seen/reviewed yet? I see it's a draft AND "[WIP]".

> facing a little difficulty in the following bullet: "Large data file versioning works by creating special files in your Git repository that point to the cache, typically stored on a local hard drive."

This refers to DVC-files. Now known simply as `.dvc` files. Explained currently in https://dvc.org/doc/command-reference/add and https://dvc.org/doc/user-guide/dvc-file-format.

> I can merge the above bullet into the beginning of the User Guide or Get Started.

Merge it how exactly? Maybe you want to add the change to this PR so we can review it?

Thanks

**Comment by jorgeorpinel** [comment]
Hello again. Please also try to fix the formatting so the CI checks pass. Please contact me with questions or if you need help @VANRao-Stack

**Comment by VANRao-Stack** [comment]
> What issue does this PR address/fix/close? Please add this basic info to the description, thanks.
> UPDATE: I see it's about #425 buried between the long text. It should be the first thing to mention in the description.

I have absorbed most of core features into the getting stated section and the user guide. Everything except Large data file versioning has been absorbed, I didn't delete the core features section.

**Comment by VANRao-Stack** [comment]
> I have worked out the case for absorbing core features.
> 
> @VANRao-Stack is this PR meant to be seen/reviewed yet? I see it's a draft AND "[WIP]".
> 
> facing a little difficulty in the following bullet: "Large data file versioning works by creating special files in your Git repository that point to the cache, typically stored on a local hard drive."
> 
> This refers to DVC-files. Also known simply as .dvc files after the 1.0 release (in progress).
> Explained currently in https://dvc.org/doc/command-reference/add and https://dvc.org/doc/user-guide/dvc-file-format
> 
> I can merge the above bullet into the beginning of the User Guide or Get Started.
> 
> Merge it how exactly? Maybe you want to add the change to this PR so we can review it?
> Thanks

Yes, I did want it to be seen. I wanted you to tell me whether this was the sort of idea you had for absorbing the core features section into rest of the documentation.

**Comment by VANRao-Stack** [comment]
> Hello again. Please also try to fix the formatting so the CI checks pass. Please contact me with questions or if you need help @VANRao-Stack

I do not exactly understand what the problem with the formatting is here exactly. When I checked their website it asked me whether I had forgotten to run Prettier. A little help please. 

Also, sorry for the late replies recently, I have been a bit sick, I will continue working continuously once I am better.

**Comment by jorgeorpinel** [comment]
Hi @VANRao-Stack. OK. One first note is: please use quotes strategically. If you quote an entire message it's not useful or informative as to what you're replying to and it makes the conversation unnecessarily long.

> Yes, I did want it to be seen. I wanted you to tell me whether this was the sort of idea you had for absorbing the core features section into rest of the documentation.

Got it. Having the PR as draft is probably enough but OK np if you also include "WIP". However, you should explicitly request the review in that case. I'll review now...

**Comment by jorgeorpinel** [comment]
> I do not exactly understand what the problem with the formatting is here exactly. When I checked their website it asked me whether I had forgotten to run Prettier.

What website do you mean? Please provide links for statements like this, try to make it easy to help you. What have you tried so far specifically? Things like this.

The CI checks are seen here:

image
> Goes to https://github.com/iterative/dvc.org/pull/1388/checks?check_run_id=729867347

From there you can click the [test](https://circleci.com/gh/iterative/dvc.org/3836) link, where you can scroll down and find which test failed. In this case it's `yarn format-check`, with the following message:

```
content/docs/user-guide/index.md
Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.
```

So, are you sure you've followed our contrib guide? I think it's been mentioned a few times already. It's found here: https://dvc.org/doc/user-guide/contributing/docs . The formatting requirements and how to enforce them locally is explained there, including running Prettier which would be done automatically had you setup a local dev environment, please do. Please go over it (again) and lmk what parts of the guide are confusing or incomplete so I can answer specific question and improve the guide.

**Comment by shcheklein** [comment]
Closing this as stale + I moved understanding DVC into UG and removed some stuff. So, need to iterate on it now.

**Pull request closed without merging**
