### PR TITLE
ug-basic-concepts-feb-21

### PR DESCRIPTION
**Pull request by iesahin**
> You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by iesahin** [comment]
This creates a Basic Concepts section under User Guide and lists several concepts. It basically merges changes from `ug-basic-concepts` branch, master as of now and changes in my fork. Some documents need revision from older docs but the _content_ of the documents will be submitted in separate PRs. 

If you think it's better to merge after all concept documents are revised, please disregard this. I will be continuing to work on `ug-basic-concept-feb-21` branch for document revisions.

**Comment by shcheklein** [comment]
@iesahin CI is still failing (pre-commit is not setup?)

@iesahin since we don't plan to merge this PR as-is I'm closing it (but we can keep iterating on a branch).

**Comment by iesahin** [comment]
@shcheklein I have three setups but the local one doesn't have `yarn develop` so I'm doing `yarn format-all` manually. (I postponed to fix `vips` install on macOS until a reasonable progress in docs.) Husky also works pre-commit. Is there a way I can deploy a branch and see the warnings without PR?

**Comment by shcheklein** [comment]
@iesahin yep, you could do a branch, push it to the project, do a WIP PR and it will be deployed automatically + you will see CI checks, etc.

**Pull request closed without merging**
