### PR TITLE
Upgrade to theme v0.2 line

### PR DESCRIPTION
**Pull request by rogermparent**
This PR integrates the latest 0.2.x line of `gatsby-theme-iterative` into the site. It also will drive some last-minute changes to how shadowing is consumed to reduce code reuse.

This PR will serve as a template for how other sites should be ported, barring colors and iterative.ai since the blog is its own beast.

### CODE REVIEW

**Review by yathomasi — APPROVED** [review]
Nice work @rogermparent. Looks good to me. Just a few minor nitpicks which can be done in the follow-up.

- Hamburger menu seems to be missing a few items. 
Screenshot 2022-11-24 at 17 19 47 Screenshot 2022-11-24 at 16 25 31

- It looks like the height of the header navbar is smaller so clicking on learn more still has a portion of the hero section still visible. It's not a priority, but UX would feel nice if it scrolls the hero section completely. 
Screenshot 2022-11-24 at 17 06 57

- It looks like not found page is missing styles
Screenshot 2022-11-24 at 17 06 39

- (Not related to the PR) I see we have an enterprise page with Typeform but it's not linked from anywhere. Do we still use it or should we remove it?

**Review by yathomasi — CHANGES_REQUESTED** [review]
I hadn't noticed this earlier. I found this while working on the theme upgrade on cml.dev.

https://dvc-org-merge-updated-t-hes5vx.herokuapp.com/doc/use-cases/ci-cd-for-machine-learning
Screenshot 2022-11-28 at 17 45 37

**Comment by rogermparent** [comment]
Thanks as always for the good review @yathomasi! Between this and https://github.com/iterative/gatsby-theme-iterative/pull/140 I've taken care of the blocker and some of the bigger nitpicks.

> * Hamburger menu seems to be missing a few items.

I had removed dvc.org's shadowed menu without regard for it providing the items. Works now that

>     * It looks like the height of the header navbar is smaller so clicking on learn more still has a portion of the hero section still visible. It's not a priority, but UX would feel nice if it scrolls the hero section completely.

I was hyper-focused on the docs and didn't think about wanting precise scrolling on elements like this. I fixed it by using `scroll-padding-top` along with `scroll-margin-top`, allowing to account for the sticky header on all elements and allow some elements to request increased scroll padding when they look better with more breathing room.

>     * It looks like not found page is missing styles

This page was depending on `@mixin`, which was removed with the theme upgrade. I've just replaced all `@mixin` declarations with equivalent Tailwind rules (we have some non-tailwindy custom utilities for `focus`, `hover`, and `active` built into the theme, but cleaning those up can be saved for another PR.

>     * (Not related to the PR) I see we have an enterprise page with Typeform but it's not linked from anywhere. Do we still use it or should we remove it?

We should remove that, but probably in another PR.

**Comment by yathomasi** [comment]
I just bumped the theme version and applied that here. Thanks, @rogermparent for taking care of all.

I am not sure what changed in [Community Learn Section](https://dvc-org-merge-updated-t-hes5vx.herokuapp.com/community#learn), the images are squeezed.
Screenshot 2022-11-30 at 12 12 23

**Comment by rogermparent** [comment]
> I just bumped the theme version and applied that here. Thanks, @rogermparent for taking care of all.
> 
> I am not sure what changed in [Community Learn Section](https://dvc-org-merge-updated-t-hes5vx.herokuapp.com/community#learn), the images are squeezed. Screenshot 2022-11-30 at 12 12 23

Looks like it may be some weirdness with Tailwind's `preflight`. I'll try to fix it and hopefully it won't require another theme bump.

Unrelated to the PR itself: this situation highlights that we'll definitely need to look into being able to run test instances with theme branches from git, the only thing really stopping us from using yarn's built-in is the monorepo structure- at least with the theme as a subpackage and not the root :thinking:.

**Comment by yathomasi** [comment]
I think the same changes can be applied to User content Images as well.
Screenshot 2022-11-30 at 22 32 51

Great work so far @rogermparent. A few minor changes can be taken to another PR. So, I am approving the PR.

**Review by yathomasi — APPROVED** [review]

**Comment by rogermparent** [comment]
Thanks! I focused on those specific images and then looked at something else. Looks like that specific element set I fixed was the only element of that kind without the `sharedStyles.link` class, so I just added those styles to `sharedStyles.link` and applied that class to the odd one out.

**Comment by rogermparent** [comment]
Everything looks fine on the self-review, nothing but nitpicks left that we can follow up on!

Speaking of which, this:

image

I had intended to let the buttons on the bottom hug the items above. Looks like it just needs `flex-basis: auto` and it'll work. I'll follow up on that later in case it affects something unintended.

**Pull request merged**
