### PR TITLE
guide: drop warnings about shallow repos

### PR DESCRIPTION
**Pull request by dberenbaum**
After https://github.com/iterative/dvc/pull/9096, this should no longer be a problem.

### CODE REVIEW

**Review by daavoo — COMMENTED** [review]
Maybe instead of completely removing it we should put a message saying to upgrade DVC? 

Users with older versions might still reach the URL via the DVC error message and they would be encountering 404

**Comment by dberenbaum** [comment]
I don't think we've done that in the past, but it's a good idea. 

@shcheklein Any concerns with this?

**Comment by shcheklein** [comment]
I think it's a reasonable thing do, thanks @daavoo ! (it won't be 404 in this case, but still it might confuse ppl).

**Comment by dberenbaum** [comment]
Great, I added the warning back with a note to upgrade versions. Since this fix isn't released yet, let's wait to merge.

**Review by omesser — APPROVED** [review]

**Comment by omesser** [comment]
@dberenbaum  - released yesterday in [dvc-2.46.0](https://github.com/iterative/dvc/releases/tag/2.46.0)
Merge?

**Pull request merged**
