### PR TITLE
doc for `dvc import --jobs`

### LINKED ISSUE #2007: New option `jobs` for `dvc import`
linked to Related to PR iterative/dvc/pull/4838

### PR DESCRIPTION
**Pull request by karajan1001**
Close #2007 per iterative/dvc/pull/4977

Only a draft one.

> You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
@karajan1001 is this still draft? I see the core PR is already merged.

**Review by jorgeorpinel — APPROVED** [review]
LGTM

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
CI fails, and there is a conflict in the restyled PR

**Comment by jorgeorpinel** [comment]
Resolved conflicts (which fixed the formatting). Merging

**Comment by jorgeorpinel** [comment]
✔️ Backported to `v1` manually

**Pull request merged**
