### PR TITLE
chore: use roboto font for docs

### PR DESCRIPTION
**Pull request by yathomasi**
- "Roboto" only for docs
- Preview: https://dvc-org-font-roboto-onl-glzpuy.herokuapp.com/

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
I like it much more than Jost; what do you think?

**Comment by shcheklein** [comment]
To me the new one looks a bit weird :) Also, not consistency (docs and outside) - which is not good. Any other fonts to try? @0x2b3bfa0 are there doc websites that you like?

**Comment by 0x2b3bfa0** [comment]
TL;DR, documentation should preferably use a clear, run-of-the-mill font.

**Comment by skshetry** [comment]
As a person with low vision, I hate the trend of these thin fonts. dvc.org is very difficult to read for me. Also, these thin fonts only look good on higher resolution displays. My 2cs.

**Comment by shcheklein** [comment]
Closing for now. Not a priority. Also we need to find better fonts I think if we want to change it.

**Pull request closed without merging**
