### PR TITLE
exp show: Drop `--pcp`.

### PR DESCRIPTION
**Pull request by daavoo**
https://github.com/iterative/dvc/pull/9270

### CODE REVIEW

**Comment by omesser** [comment]
@daavoo (& @dberenbaum ) - is this blocked until https://github.com/iterative/dvc/pull/9270 is merged and released (3.0 release), or did you plan to deprecate the docs beforehand, so people stop using it ASAP

**Review by omesser — APPROVED** [review]

**Comment by omesser** [comment]
@daavoo @dberenbaum  - marking blocked for now but that's only based on my understanding of you rather waiting for the release or to plan a deprecation notice.
If that's not the case please remove the label and merge

**Review by dberenbaum — APPROVED** [review]

**Review by dberenbaum — CHANGES_REQUESTED** [review]
@daavoo Let's add a deprecation notice and merge.

**Comment by daavoo** [comment]
> @daavoo Let's add a deprecation notice and merge.

How/Where should I add the `deprecation notice`?

**Comment by dberenbaum** [comment]
There's an example one in https://dvc.org/doc/user-guide/project-structure/configuration#state.

Let's put a note under the `exp show` synopsis listing all the options to be deprecated in 3.0.

**Comment by daavoo** [comment]
> There's an example one in https://dvc.org/doc/user-guide/project-structure/configuration#state.
> 
> Let's put a note under the `exp show` synopsis listing all the options to be deprecated in 3.0.

I feel like with 3.0 we will be bloating the docs with this kind of notes. Goes back to the versioned ref discussion 😅

**Comment by dberenbaum** [comment]
> I feel like with 3.0 we will be bloating the docs with this kind of notes. Goes back to the versioned ref discussion 😅

For a deprecated option, I don't think we need to keep explaining what it did, but it would be nice to explain that it was deprecated so people know why a command breaks on upgrade, or why they might see an option in the CLI for an old version but can't find it in the docs. 

It can be as simple as this:

```
<details>

### Options deprecated in 3.0

* `--pcp`

</details>
```

We are giving almost no lead time for these deprecations, so it seems reasonable to have some kind of notice. We don't have to commit to how long we want to maintain these notices, but right now I think it's unclear to users sometimes whether the docs are missing things or we have intentionally deprecated them.

**Comment by dberenbaum** [comment]
@daavoo Can we get this and #4441 merged when you have a chance?

**Comment by dberenbaum** [comment]
Since the deprecation notice seems to be blocking AND experiments were "experimental" for 2.x AND we already deprecated other `exp` commands and options without warning, let's merge these without a notice to get it merged.

**Review by dberenbaum — APPROVED** [review]

**Pull request merged**
