### PR TITLE
[TEST] changed version, link checker must fail

### PR DESCRIPTION
**Pull request by iesahin**
Context: https://github.com/iterative/dvc.org/pull/2725#issuecomment-901922726

### CODE REVIEW

**Comment by iesahin** [comment]
The download links in the deployment are not checked by the link checker. 

image

It can't find these links: 

image

@shcheklein @jorgeorpinel @efiop

**Comment by iesahin** [comment]
Because the link checker works on `.md` files. 💡 😆 

I think something works on the deployment might be better for generated links like these. WDYT? @shcheklein @jorgeorpinel

**Comment by shcheklein** [comment]
> I think something works on the deployment might be better for generated links like these.

@iesahin could you clarify please :) ?

@julieg18 has been working on CI/CD check specifically for the download button links here https://github.com/iterative/dvc.org/issues/2579 https://github.com/iterative/dvc.org/pull/2660 - it's not done yet though

**Comment by iesahin** [comment]
> @iesahin could you clarify please :) ?

Does the link checker work on `.md` files? I thought so. My mistake. :)

**Comment by jorgeorpinel** [comment]
Sounds like we can close this, please reopen otherwise. Thanks

**Pull request closed without merging**
