### PR TITLE
test(website): testing download link check

### PR DESCRIPTION
**Pull request by shcheklein**
> You may disregard these recommendations if you used the **Edit on GitHub** button from dvc.org to improve a doc in place.

❗ Please read the guidelines in the [Contributing to the Documentation](https://dvc.org/doc/user-guide/contributing/docs) list if you make any substantial changes to the documentation or JS engine.

🐛 Please make sure to mention `Fix #issue` (if applicable) in the description of the PR. This causes GitHub to close it automatically when the PR is merged.

Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to edit your branch when creating the PR.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by shcheklein** [comment]
@yathomasi getting a broken restyle check - anything that you are aware of / or see from the top of your head?

**Comment by yathomasi** [comment]
@shcheklein 
 - It had happened before as well. 
- https://github.com/restyled-io/restyler/issues/204
- The error is `Error: Cannot find module '@dvcorg/gatsby-theme-iterative/tailwind.config'`
- According to them, they don't download the package and only include them if it was a standard package or want us to use a custom Restyler Image. [source](https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-Prettier#cannot-find-module-)
- It should be okay to ignore it for now.

**Comment by shcheklein** [comment]
> It should be okay to ignore it for now; if we want to deploy, we should manually trigger it. Let me trigger the build on Heroku.

thanks @yathomasi  ... will it be fixed by itself? not sure I understand what is the plan for this

**Comment by yathomasi** [comment]
@shcheklein I meant to ignore for now so that you could test the `download link check` functionality.

I created a issue for that: https://github.com/iterative/dvc.org/issues/4553. I am not sure of the priority as it will be working for content(markdown files). Anyway, solution looks straight forward it just need us to create a docker image and host ourselves.

**Pull request closed without merging**
