### PR TITLE
Use `youtube-nocookie` domain in Video component

### PR DESCRIPTION
**Pull request by julieg18**
Part of #2980

### CODE REVIEW

**Comment by shcheklein** [comment]
Interesting, in the incognito mode I local storage is clean and I see two cookies `NID` and `1P_JAR` 🤔

**Review by rogermparent — APPROVED** [review]
Looks good! This should handle all our embeds since `gatsby-remark-embedder` uses `nocookie` automatically.

**Comment by shcheklein** [comment]
I wonder also if the set different things in different countries/regions.

**Comment by rogermparent** [comment]
Just grabbed a random GDPR checker, assuming it checks from EU, and found something interesting:

https://www.cookiemetrix.com/display-report/dvc-org-use-youtube-noc-nchy4d.herokuapp.com/d31ca1f42e90bf8768df44de574e4ee3

There's one stored cookie: `CONSENT` from `youtube-nocookie.com` with the value `PENDING+342`. I'd imagine this specific cookie could be exempt since it isn't tracking the user, just a setting, and it does serve a technical purpose in remembering whether the user has consented to cookies.

**Comment by shcheklein** [comment]
Also things to keep in mind (regarding different regions and countries).

For example, when I open youtube.com itself in the empty newly installed Firefox - it doesn't ask anything at all regarding cookies (and I'm pretty sure they have to be 100% compliant with CA laws). I wonder what happens if we open it from Europe.

Just saying that we should be ideally doing checks from some European country with an empty browser (user is not logged in into Youtube and didn't accepted anything).

**Comment by shcheklein** [comment]
Tested clean Safari and Firefox from CA - no cookies, only some non-essential local store things like:

Screen Shot 2022-01-05 at 9 39 51 AM

Can't test completely clean Chrome. And can't test from Europe now.

But so far it looks reasonable for me.

**Pull request merged**
