### PR TITLE
metrics: update metrics.show() documentation

### PR DESCRIPTION
**Pull request by cand126**
Updating the documentation according to this PR: https://github.com/iterative/dvc/pull/1809

### CODE REVIEW

**Comment by shcheklein** [comment]
@cand126 thanks! does it work the same way for `dvc repro -m`? btw? cc @efiop

**Comment by shcheklein** [comment]
@cand126 Also, if we detect type automatically, do we apply `-x` as well or is it ignored it `-t` is not specified explicitly?

**Comment by efiop** [comment]
@shcheklein `-x` overwrites any xpath specified previously. And yes, it works the same way for `dvc repro -m`.

**Comment by shcheklein** [comment]
@efiop what happens if -t is not specified but auto-detected, do we apply -x as well or do we ignore it?

**Comment by efiop** [comment]
@shcheklein yes, we apply `-x`.

**Comment by shcheklein** [comment]
@efiop thanks! we'll need to update the documentation a little bit.

**Comment by efiop** [comment]
@shcheklein Yes, sorry, didn't catch that one right away. Thanks for the heads up!

**Comment by cand126** [comment]
@shcheklein 

- `dvc repro -m` does not detect the file type automatically
- The `--xpath` argument still works with file type detection. For example, `dvc metrics show --xpath=AUC` lists the values of **AUC** column

**Comment by cand126** [comment]
@shcheklein do I also need to update the documentation for `dvc repro -m`?

**Comment by efiop** [comment]
@cand126 We would definitely appreciate it if you'd be so kind :) Issue for that is https://github.com/iterative/dvc.org/issues/229 .

**Pull request merged**
