### PR TITLE
redirects: add man.dvc.org/completion

### PR DESCRIPTION
**Pull request by dtrifiro**
Fixes 404 on https://man.dvc.org/completion

### CODE REVIEW

**Review by iesahin — APPROVED** [review]
Thank you Daniele.

**Comment by shcheklein** [comment]
@dtrifiro thanks! out of curiosity - can we pls provide more context to the PR? where do we have this link in DVC?

**Comment by dtrifiro** [comment]
Hey, this comes from `dvc completion --help`:
image

**Comment by shcheklein** [comment]
Thanks, makes sense. Should we then have a CR page - https://dvc.org/doc/command-reference/completion? We can link from it the guide in Install ... also we need to add syntax highlighter for `dvc completion` I guess. cc @jorgeorpinel @iesahin

**Comment by jorgeorpinel** [comment]
> Should we then have a CR page - https://dvc.org/doc/command-reference/completion?

Due to this PR that URL has been permanently redirected to https://dvc.org/doc/install/completion :/ we should undo this ASAP if we want to have the cmd ref. And I agree we should! Not sure how that slept through (probably a while ago). @dberenbaum WDYT?

**Comment by jorgeorpinel** [comment]
> For now I would make the redirect temporary (302 code) to avoid permanent 301 cache.

Made https://github.com/iterative/dvc.org/pull/3172

Cc @iesahin please keep in mind the nature or permanent redirects before merging redirect changes 🙂 We should carefully consider which ones go 302 or even 303 I think.

**Comment by jorgeorpinel** [comment]
And/or... Maybe the engine should default to 302 and we make 301s explicit?

**Pull request merged**
