### PR TITLE
azure: remove note about bucket autocreation

### PR DESCRIPTION
**Pull request by efiop**
Per https://github.com/iterative/dvc/pull/6086#issuecomment-857287644

### CODE REVIEW

**Review by jorgeorpinel — APPROVED** [review]

**Comment by jorgeorpinel** [comment]
Thanks @efiop !

Do you think we should state somewhere (or in all the appropriate remotes) that DVC **does not** create buckets/containers? Cc @dberenbaum

**Comment by dberenbaum** [comment]
Personally, I wouldn't expect DVC to create buckets, but maybe others would, and it probably can't hurt to be explicit.

**Comment by jorgeorpinel** [comment]
You're right. Let's skip it unless we see that it causes confusion with users 👍

**Comment by dberenbaum** [comment]
What was the context for trying to create buckets in the first place?

**Comment by efiop** [comment]
@dberenbaum Lack of standards when it was first contributed and hesitation to break the existing behavior until now.

**Pull request merged**
