### PR TITLE
guide: split Comparing Experiments, move Listing content to a new document

### PR DESCRIPTION
**Pull request by iesahin**
This splits UG: Comparing Experiments page by removing `dvc exp list` related content to a new page. Adds the new page to the sidebar. 

No content changes except the initial sentence in Listing Experiments.

Related #2995

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
Not sure about thi. We'd have 2 pages that are closely related and now you have to navigate some of it on the left nav. May be confusing and the structure isn't clear. Why "compare" before "list" (nav)?

I think we should first try to summarize the current https://dvc.org/doc/user-guide/experiment-management/comparing-experiments significantly to address some of the tasks in #2995.

**Comment by jorgeorpinel** [comment]
p.s. and yes I realize this was one idea we had while reviewing the original PR but seeing it now it's not making much sense to me. Idk what we gain from this.

**Comment by iesahin** [comment]
I can push _Listing_ below in the sidebar. 

This was the easiest way to shorten the section. We can summarize the content in a cascading PR.

**Comment by jorgeorpinel** [comment]
> We can summarize the content in a cascading PR.

If we're not separating into 2 pages why cascade it though?

**Comment by iesahin** [comment]
What do you recommend to do?

**Comment by jorgeorpinel** [comment]
I think we can close this and discuss/address the bullets in https://github.com/iterative/dvc.org/issues/2995.

**Comment by iesahin** [comment]
Close per your recommendation. We can discuss this in #2995

**Comment by jorgeorpinel** [comment]
Thanks. Agreed.

**Pull request closed without merging**
