### PR TITLE
admon: use/replace book icons

### PR DESCRIPTION
**Pull request by jorgeorpinel**
After https://github.com/iterative/gatsby-theme-iterative/pull/76

- [x] Wait for ☝🏼 to propagate to this site.

### CODE REVIEW

**Comment by jorgeorpinel** [comment]
> Wait for (https://github.com/iterative/gatsby-theme-iterative/pull/76) to propagate to this site.

Hi @rogermparent just curious: how long should the update change here? Thanks

**Comment by yathomasi** [comment]
@jorgeorpinel Sorry, for the blocker. It shouldn't have taken long and I had already tried to bump the theme ([PR](https://github.com/iterative/dvc.org/pull/3952)) but theme has other issue so it was halted. 

Roger was working with the fix/solution (https://github.com/iterative/gatsby-theme-iterative/pull/79). He seems to be busy. So, I will be taking over and ship it as soon as possible.

**Comment by rogermparent** [comment]
The theme update to 0.1.15 has the book icon, and it should be coming in via Renovate, but I don't see a PR. Maybe https://github.com/iterative/dvc.org/pull/3951 somehow caused the update not to appear?

**Comment by jorgeorpinel** [comment]
> Sorry, for the blocker

No rush here, don't worry.

> Maybe #3951 somehow caused the update not to appear?

¯\_(ツ)_/¯  I'll resolve conflicts for now.

**Review by yathomasi — APPROVED** [review]
Looks good to me. The [preview](https://dvc-org-admons-book-ico-ydyvs8.herokuapp.com/doc/command-reference/exp#description) seems to be fine:

Screen Shot 2022-09-22 at 13 49 12

**Pull request merged**
