### PR TITLE
ref/remote: tabify & crossref config

### PR DESCRIPTION
**Pull request by casperdcl**
Because hyperlinkable docs are awesomer

- related #2939
- related #1859
- related #2866
- related #1699

# Before

https://dvc.org/doc/command-reference/remote/modify#available-parameters-per-storage-type

image

# After

https://dvc.org/doc/command-reference/remote/modify?tab=Aliyun-OSS#available-parameters-per-storage-type

image

### CODE REVIEW

**Comment by shcheklein** [comment]
A few concerns (mainly that it doesn't change much and doesn't solve the problem):

- it's still not exactly linkable (you are sending link to a subsection still at best). I'm not sure this changes experience much - when open the subsection you see all the titles in one page now
- long term it should be addresses in some other epics where we want to get it out into separate pages. Clearly content is too large for tabs, subsections, and hidden sections
- I personally don't like that by default now it'a a huge long S3 section that is visible. Not sure this is the best experience.

**Comment by casperdcl** [comment]
I :100: agree it doesn't solve *the* problem. However it solves *a* problem to me.

> when open the subsection you see all the titles in one page now

I suppose that's a separate `A: website` issue?

> default now it'a a huge long S3 section

We could reorder to have a shorter default?

**Comment by shcheklein** [comment]
> However it solves a problem to me.

I assume ability to link to a specific section? Fair enough, but let's do it quick - just move all into section or make expandable blocks linkable - I think it should not be a problem and we could do it quick cc @iterative/websites 

> I suppose that's a separate A: website issue?

What I wanted to say is that current experience (link - https://dvc.org/doc/command-reference/remote/modify#available-parameters-per-storage-type) gives you very similar experience (or I don't understand _a_ problem):

Screen Shot 2022-02-18 at 7 05 59 PM

I see all the available options there. 

Or do you mean something else?

> We could reorder to have a shorter default?

Not good I guess, since S3 is _the_ default these days

WDYT?

**Comment by casperdcl** [comment]
> move all into section

not sure what this means; sounds like #2866 and/or #1699

> or make expandable blocks linkable

sure, that sounds good to me.

**Comment by jorgeorpinel** [comment]
So does https://github.com/iterative/dvc.org/issues/3314 solve this?

**Comment by casperdcl** [comment]
> So does #3314 solve this?

Partially. Would probably still have to delete "Click for " prefixes.

**Comment by casperdcl** [comment]
replaced by #3329

**Pull request closed without merging**
